---
title: "Extent Tab"
subtitle: "Product Records"
editor: 
  markdown: 
    wrap: 80
---

```{r, echo=FALSE}
# Using colors from this wesbite:
# https://designsystem.digital.gov/design-tokens/color/state-tokens/
# This allows the colors to be coded as a variable and, thus, easily changed.

required_color <- "#b50909"        #'red-60v'
if_applicable_color <- "#947100"   # 'yellow-50v'
best_practice_color <- "#00687d"   # 'cyan-60v'
other_color <- "#00687d"           # 'gray-cool-70'
req_style <- paste0('{style="color:', required_color, ';"}')
if_style <- paste0('{style="color:', if_applicable_color,';"}')
best_style <- paste0('{style="color:', best_practice_color, ';"}')
other_style <- paste0('{style="color:', best_practice_color, ';"}')
```

**Extent** refers to geographic boundaries for your project. Spatial extents
lets users see at a glance the geographic footprint of your project and allows
searching within specific geographic areas.

### Extent Tab 
| Metadata Field                      | Product Records   |
|:------------------------------------|:----------|
| Extent | [**Required**](#creating-extents)`r req_style` |
: {.striped .hover .bordered .sm .allborder}  

<br/>

Spatial extents should be included for all applicable products. As a default,
products should inherit extents from their parent project. geoJSON files for
specific geographies are available on
[ScienceBase](https://www.sciencebase.gov/catalog/item/5bd7c96fe4b0b3fc5ce82d44)
(private DMWG folder that requires ScienceBase login). Download the relevant
files and then import the geoJSON files into mdEditor.

:::{.callout-tip}
Tip: You can export, save, and import an extent to use for other projects or 
products.
:::

See further information on Extents in the [Project Extent entry guidance](../project_records/extent_tab_project.qmd).
