---
title: "Product Records: Overview"
editor: 
  markdown: 
    wrap: 80
---

The Product Records section will cover how to create a metadata record for a
product. A product can be anything from a document or presentation or website to
a dataset or programming code. mdEditor offers an extensive list of product
options, of which "**product**" should never be used.

## Before You Begin

#### 1. Adjust mdEditor Settings

**Metadata Repositories**: Make sure your default settings are correct for the
SA Science Catalog and Data.gov. See [Settings](../settings.qmd).

**Parent Identifier**: In the publishing settings, enter your SA regional
ScienceBase project folder's identifier in the "Default Parent Identifier"
field.

#### 2. Select the "Product" Profile:

After initially creating your project record, but before you begin adding
metadata, select the metadata record's profile type. In the main menu's
**Profile** drop-down options, select "**Product**". This will limit the
number of available tabs and only show tabs that contain fields that are
required for product creation.

![Select the Product profile in the Profile dropdown in the top
ribbon](../../assets/product_profile_from_dropdown.png)

#### 3. Ensure Contacts are loaded into mdEditor:

In mdEditor, contacts are created separately from individual records, and then
stored within a library in mdEditor. Once contacts have been entered or imported
into mdEditor, they can be used in metadata records. 

SA has a "seed list" of contacts that that contains standardized information 
for common partner agencies, USFWS regions, and the SA Network Data Steward. 
This **Contacts Seed** file (as a .json) can be downloaded from the
[mdEditor Seed Contacts item page](https://www.sciencebase.gov/catalog/item/5df8d2b7e4b0cdded73b4069).
and then imported into mdEditor using the 
[Import](../metadata_file_management/import_mdjson.qmd) tab.

## Edit a Product

1.  Import or create your product record (see
    [workflow](../metadata_workflows/metadata_workflows_overview.qmd)).
2.  Choose the specific **Resource Type** that describes your product. Do not
    choose the generic "product."
3.  Select the Product Profile: from the Main Menu (Top Navigation Bar) select
    "**Product"** from the profile drop-down menu.
4.  Fill out metadata information for the following tabs:\
          [Main Tab](main_tab_product.qmd)\
          [Metadata Tab](metadata_tab_product.qmd)\
          [Keywords Tab](keywords_tab_product.qmd)\
          [Taxonomy Tab](taxonomy_tab_product.qmd)\
          [Extent Tab](extent_tab_product.qmd)\
          [Lineage Tab](lineage_tab_product.qmd)\
          [Distribution Tab](distribution_tab_product.qmd)\
          [Constraints Tab](constraints_tab_product.qmd)\
          [Dictionaries Tab](dictionaries_tab_product.qmd)\
          [Documents Tab](documents_tab_product.qmd)\
5.  If applicable, the [Associated Tab](associated_tab_product.qmd) allows your 
    product to be associated with other metadata records.

```{=html}
<!-- 
################### START OF COMMENTED OUT CODE ################################ 

## Required Fields for Products

### Main Tab

-   Title
-   Status
-   Language
-   Resource Type
-   Point of Contact
-   Main Citation
    -   Title
    -   Identifier
    -   Responsible Parties
    -   Online Resource URI
-   Description
    -   Abstract
-   Time Period
    -   Start Date
    -   End Date

### Metadata Tab

-   Metadata Status
-   Date
-   Metadata Contacts
-   Metadata Identifier
-   Parent Metadata
    -   Title
    -   Identifier
    -   Namespace
-   Metadata Repositories
-   Online Resource

### Extent Tab

-   Geographic Extent

### Keywords Tab

-   ISO Topic Category
-   SA Priority Area Category
-   SA Science Category
-   Conservation Action Open Standard
-   GCMD Keywords (Best Practice)

### Taxonomy Tab

-   Taxonomic classifications

### Extent Tab

-   Geographic Extent

### Distribution Tab

-   Distributor
    -   Contact
    -   Role
    -   Online Option
        -   URI

### Constraints

-   Legal
    -   Access Constraint
    
################### END OF COMMENTED OUT CODE ################################ 
-->
```
