---
title: "Publishing: Overview"
editor: 
  markdown: 
    wrap: 80
---

**Note**: The Publishing instructions still need some editing and refinement.

SA metadata is currently published to ScienceBase in your [SA Region folder](https://www.sciencebase.gov/catalog/item/645bfdf8d34ec179a83822c0). You 
must have a ScienceBase user account with write access to this
folder. Once the mdJSON metadata is published in ScienceBase, the records will
be synced with the [SA Science Catalog](https://www.fws.gov/science/catalog) (the Science Catalog updates overnight
with new/updated mdJSON).

## Before You Begin

Please read through **all** instructions before you begin the publishing process.
After you understand how the publishing function works, please read
the [**Testing**](testing.qmd) section and publish a test record before trying 
to publish any real records.

## Publishing to the Science Catalog Process Overview

The following describes what happens when you publish from mdEditor:

1.  mdEditor outputs an mdJSON file.
2.  The mdJSON file is transmitted to the SBMB web service API.
3.  The SBMD service sends the mdJSON file to mdTranslator.
4.  mdTranslator translates the mdJSON file into a sbJSON file and two XML files:
    metadata.xml (ISO 19915-2) and metadata_iso1.xml (IS 19115-1).
5.  The SBMD service sends the sbJSON file to the [ScienceBase API](https://www.usgs.gov/sciencebase-instructions-and-documentation/api-and-web-services), which creates (or updates) the ScienceBase item.
6.  The SBMD service attaches the XML and mdJSON files to the ScienceBase item.
7.  The ScienceBase record is sent to data.doi.gov and the [SA Science Catalog](https://www.fws.gov/science/catalog), if the
    requisite metadata repositories are specified.
