project: 
  type: website

website: 
  page-navigation: true
  title: "USFWS Science Applications - Metadata Guidance" 
  site-url: "https://studious-adventure-wo15nv1.pages.github.io" 
  repo-url: "https://github.com/usfws/sciapps_metadata_guidance"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://www.fws.gov/themes/custom/fws_gov/logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://fws.gov
        text: "USFWS"
      - icon: github
        href: https://github.com/usfws
        text: "USFWS Github"

    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - content/01_roles_and_responsibilities.qmd
      - content/02_goals_sa_data_management.qmd   
      - content/03_sa_science_catalog.qmd   
      - content/04_projects_products_contacts.qmd   
      - content/05_non_duplication_policy_guidance.qmd   
      - section: "Metadata"
        contents:
          - content/06a_metadata_from_scratch.qmd
          - content/06b_metadata_sciencebase_first.qmd          
          - content/06c_metadata_editing_republishing.qmd          
          - content/06d_metadata_pts_considerations.qmd 
      - content/07_settings.qmd           
      - section: "mdEditor Metadata File Management"
        contents:
          - content/08_MDEditor_Metadata_File_Management/08a_import_intro.qmd    
          - section: "Import"
            contents:
            - content/08_MDEditor_Metadata_File_Management/08b_import.qmd
            - content/08_MDEditor_Metadata_File_Management/08c_import_mdjson.qmd          
            - content/08_MDEditor_Metadata_File_Management/08d_import_sbjson.qmd          
            - content/08_MDEditor_Metadata_File_Management/08e_import_fgdc.qmd          
          - content/08_MDEditor_Metadata_File_Management/08f_export.qmd   
          - content/08_MDEditor_Metadata_File_Management/08g_copy_records.qmd   
      - content/09_metadata_requirements_checklist.qmd  
      - content/10_digital_object_identifier.qmd        
      
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
