project: 
  type: website

language: 
  search-box-placeholder: "Search" # Currrently not working. Old version? 

website: 
  page-navigation: true
  title: "USFWS Science Applications - Metadata Guidance QUARTO" 
  site-url: "https://studious-adventure-wo15nv1.pages.github.io" 
  repo-url: "https://github.com/usfws/sciapps_metadata_guidance"
  repo-actions: [edit, issue]
  favicon: favicon.png
  search:
    location: sidebar
    type: textbox
  
  sidebar:
    title: "USFWS Science Applications Metadata Guidance"   
    background: "#D9E3E4"
    logo: "/assets/usfws_logo_64px_width.png"
    favicon: favicon.ico
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/USFWS/sciapps_metadata_guidance
        text: "Github Repo"
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: content/roles_and_responsibilities.qmd
        text: "Roles and Responsibilities"
      - content/goals_sa_data_management.qmd   
      - content/sa_science_catalog.qmd   
      - content/projects_products_contacts.qmd   
      - content/non_duplication_policy.qmd   
      - section: "Workflow"
        contents:
          - href: content/workflow/workflow_overview.qmd
            text: "Overview"
          - content/workflow/metadata_from_scratch.qmd
          - content/workflow/metadata_sciencebase_first.qmd          
          - content/workflow/metadata_editing_republishing.qmd          
          - href: content/workflow/metadata_project_tracking_system_considerations.qmd
            text: "Project Tracking System Considerations"
      - content/settings.qmd           
      - section: "mdEditor File Management"
        contents:
          - content/mdeditor_metadata_file_management/metadata_file_management.qmd    
          - section: "Import"
            contents:
            - content/mdeditor_metadata_file_management/import_import_settings.qmd
            - content/mdeditor_metadata_file_management/import_mdjson.qmd          
            - content/mdeditor_metadata_file_management/import_sbjson.qmd          
            - content/mdeditor_metadata_file_management/import_fgdc.qmd          
          - content/mdeditor_metadata_file_management/export.qmd   
          - content/mdeditor_metadata_file_management/copy_records.qmd   
      - content/metadata_requirements_checklist.qmd  
      - href: content/digital_object_identifier.qmd        
        text: "Digitial Object Identifier"
      - section: "Project Records"
        contents:
          - href: content/project_entry_guidance/overview_project.qmd
            text: "Overview"        
          - content/project_entry_guidance/main_tab_project.qmd          
          - content/project_entry_guidance/metadata_tab_project.qmd          
          - content/project_entry_guidance/keywords_tab_project.qmd          
          - content/project_entry_guidance/taxonomy_tab_project.qmd          
          - content/project_entry_guidance/extent_tab_project.qmd          
          - content/project_entry_guidance/documents_tab_project.qmd          
          - content/project_entry_guidance/funding_tab_project.qmd           
          - content/project_entry_guidance/associating_records_project.qmd          
      - section: "Product Records"
        contents:
          - href: content/product_entry_guidance/overview_product.qmd
            text: "Overview"        
          - content/product_entry_guidance/main_tab_product.qmd          
          - content/product_entry_guidance/metadata_tab_product.qmd  
          - content/product_entry_guidance/datagov_guidance_product.qmd 
          - content/product_entry_guidance/keywords_tab_product.qmd          
          - content/product_entry_guidance/taxonomy_tab_product.qmd          
          - content/product_entry_guidance/extent_tab_product.qmd          
          - content/product_entry_guidance/lineage_tab_product.qmd   
          - content/product_entry_guidance/distribution_tab_product.qmd       
          - content/product_entry_guidance/constraints_tab_product.qmd       
          - content/product_entry_guidance/dictionaries_tab_product.qmd       
          - content/product_entry_guidance/documents_tab_product.qmd       
          - content/product_entry_guidance/associating_records_product.qmd       
      - section: "Contact Records"
        contents:
          - href: content/contact_entry_guidance/contact_entry_guidance_overview.qmd
            text: "Overview"
          - content/contact_entry_guidance/summary_contact_requirements.qmd
          - content/contact_entry_guidance/individual_contacts.qmd
          - content/contact_entry_guidance/organization_contacts.qmd
      - section: "Co-Funded Project Protocols"
        contents:
          - href: content/cofunded_project_protocols/cofunded_projects_overview.qmd
            text: "Overview"         
          - content/cofunded_project_protocols/collaboration_protocol.qmd
          - section: "Sub-Project Protocol"          
            contents: 
              - href: content/cofunded_project_protocols/subproject_protocol_overview.qmd
                text: "Overview"
              - content/cofunded_project_protocols/subproject_of_fws_region_program_project.qmd
              - content/cofunded_project_protocols/subproject_of_casc_project.qmd
          - section: "Co-Funded Protocol"          
            contents: 
              - href: content/cofunded_project_protocols/cofunded_protocol_overview.qmd
                text: "Overview"
              - content/cofunded_project_protocols/fws_cofunded_projects.qmd
              - content/cofunded_project_protocols/fws_casc_projects_products.qmd
              - content/cofunded_project_protocols/casc_responsibilites.qmd
              - content/cofunded_project_protocols/lcc_examples.qmd
      - section: "Publishing"
        contents:
          - href: content/publishing/publishing_overview.qmd
            text: "Overview"
          - content/publishing/requirements_for_publishing.qmd
          - content/publishing/testing_publishing.qmd
          - content/publishing/how_to_publish.qmd          
          - content/publishing/republishing.qmd          
      - content/archiving_requirements.qmd
      - section: "Trouble-Shooting Tips"
        contents:
          - href: content/trouble_shooting_tips/trouble_shooting_tips_overview.qmd      
            text: "Overview"
          - content/trouble_shooting_tips/qa_qc_fixes.qmd      
          - content/trouble_shooting_tips/qa_qc_resources.qmd      
      - section: "Bulk Editing Resources"
        contents:
          - content/bulk_editing_resources/injector_script_overview.qmd      
          - content/bulk_editing_resources/injector_script_funding.qmd      
          - content/bulk_editing_resources/injector_script_distribution_links.qmd 
      - content/help.qmd
      - content/glossary_of_terms.qmd

format:
  html:
    toc: true
    theme:
      light: [materia, theme.scss]
      dark: [materia, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px
      
filters:
  - include-files.lua
  - quarto

  
