project: 
  type: website

language: 
  search-box-placeholder: Search # Currrently not working. Change in css? 

website: 
  page-navigation: true
  title: "USFWS Science Applications Metadata Guidance" 
  site-url: "https://usfws.github.io/Science_Applications_Metadata_Guidance/" 
  repo-url: "https://github.com/usfws/sciapps_metadata_guidance"
  repo-actions: [edit, issue]
  favicon: favicon.png
  # code-links:
  #   - text: Open Issue in Github
  #     icon: github 
  #     href: https://github.com/USFWS/Science_Applications_Metadata_Guidance/issues/new
  #   - text: Provide Feedback via a Form
  #     icon: pencil-square 
  #     href: https://forms.office.com/g/xtkDZ3rQjW  
  other-links:
    # - text: Open Issue in Github
    #   icon: github 
    #   href: https://github.com/USFWS/Science_Applications_Metadata_Guidance/issues/new
    - text: Provide User Feedback
      icon: pencil-square
      href: https://forms.office.com/g/xtkDZ3rQjW
  search:
    location: sidebar
    type: textbox
  sidebar:
    title: "USFWS Science Applications Metadata Guidance"   
    background: "#D9E3E4"
    logo: "/assets/usfws_logo_64px_width.png"
    favicon: favicon.ico
    pinned: true
    align: center
#    tools:
#      - icon: github
#        href: https://github.com/USFWS/sciapps_metadata_guidance
#        text: "Github Repo"
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: content/roles_and_responsibilities.qmd
        text: "Roles and Responsibilities"
      - content/data_management_goals.qmd   
      - content/science_catalog.qmd   
      - content/projects_products_contacts.qmd   
      - section: "Metadata Workflows"
        href: content/metadata_workflows/metadata_workflows_overview.qmd
        contents:
          - content/metadata_workflows/from_scratch.qmd
          - content/metadata_workflows/sciencebase_first.qmd          
          - content/metadata_workflows/editing_republishing.qmd          
      - content/settings.qmd           
      - section: "Metadata File Management"
        href: content/metadata_file_management/metadata_file_management_overview.qmd    
        contents:
          - section: "Import"
            href: content/metadata_file_management/import_overview.qmd
            contents:
            - content/metadata_file_management/import_mdjson.qmd          
            - content/metadata_file_management/import_sbjson.qmd          
            - content/metadata_file_management/import_fgdc.qmd          
          - content/metadata_file_management/export.qmd   
          - content/metadata_file_management/copy_records.qmd   
      - content/metadata_requirements.qmd  
#      - href: content/digital_object_identifier.qmd        
#        text: "Digitial Object Identifier"
      - section: "Project Records"
        href: content/project_records/project_records_overview.qmd
        contents:
          - content/project_records/main_tab_project.qmd          
          - content/project_records/metadata_tab_project.qmd          
          - content/project_records/keywords_tab_project.qmd          
          - content/project_records/extent_tab_project.qmd          
          - content/project_records/taxonomy_tab_project.qmd          
          - content/project_records/associated_tab_project.qmd          
          - content/project_records/documents_tab_project.qmd          
          - content/project_records/funding_tab_project.qmd           
      - section: "Product Records"
        href: content/product_records/product_records_overview.qmd
        contents:
          - content/product_records/main_tab_product.qmd          
          - content/product_records/metadata_tab_product.qmd  
          - content/product_records/datagov_guidance_product.qmd 
          - content/product_records/keywords_tab_product.qmd          
          - content/product_records/extent_tab_product.qmd          
          - content/product_records/lineage_tab_product.qmd   
          - content/product_records/taxonomy_tab_product.qmd          
          - content/product_records/distribution_tab_product.qmd       
          - content/product_records/constraints_tab_product.qmd       
          - content/product_records/associated_tab_product.qmd       
          - content/product_records/documents_tab_product.qmd       
          - content/product_records/dictionaries_tab_product.qmd       
      - section: "Contact Records"
        href: content/contact_records/contact_records_overview.qmd
        contents:
          - href: content/contact_records/contact_requirements_summary.qmd
            text: "Metadata Record Contact Requirements"
          - content/contact_records/individual_contacts.qmd
          - content/contact_records/organization_contacts.qmd
      - section: "Co-Funded Projects"
        href: content/cofunded_project_protocols/cofunded_projects_overview.qmd
        contents:
          - content/cofunded_project_protocols/collaboration_protocol.qmd
          - section: "Sub-Project Protocol"          
            href: content/cofunded_project_protocols/subproject_protocol_overview.qmd
            contents: 
              - content/cofunded_project_protocols/subproject_of_fws_region_program_project.qmd
              - content/cofunded_project_protocols/subproject_of_casc_project.qmd
          - section: "Co-Funded Protocol"          
            href: content/cofunded_project_protocols/cofunded_protocol_overview.qmd
            contents: 
              - content/cofunded_project_protocols/fws_cofunded_projects.qmd
              - content/cofunded_project_protocols/fws_casc_projects_products.qmd
              - content/cofunded_project_protocols/casc_responsibilites.qmd
      - section: "Publishing"
        href: content/publishing/publishing_overview.qmd
        contents:
          - content/publishing/requirements.qmd
          - content/publishing/testing.qmd
          - content/publishing/how_to.qmd          
          - content/publishing/republishing.qmd          
      - content/feedback_help.qmd
      - section: "Appendix"
        href: content/appendix/appendix_overview.qmd 
        contents:
#          - section: "Developer Resources"
#            href: content/developer_resources/developer_resources_overview.qmd        
#            contents:
#              - section: "Injector Script"
#                href: content/developer_resources/injector_script/injector_script_overview.qmd      
#                contents:
#                  - content/developer_resources/injector_script/example_funding.qmd      
#                  - content/developer_resources/injector_script/example_distribution_links.qmd         
          - section: "LCC Workflows"
            href: content/appendix/lcc_workflows/lcc_workflows_overview.qmd      
            contents:
              - content/appendix/lcc_workflows/cofunded_lcc_projects.qmd      
          - content/appendix/non_duplication_policy.qmd   
      - content/glossary.qmd
            
#      - content/archiving.qmd
#      - section: "Trouble-Shooting"
#        href: content/trouble_shooting/trouble_shooting_overview.qmd      
#        contents:
#          - content/trouble_shooting/qa_qc_fixes.qmd      
#          - content/trouble_shooting/qa_qc_resources.qmd    
#        - section: "Project Tracking System - Region 6"  
#          href: content/appendix/project_tracking_system/project_tracking_system_considerations.qmd
#          contents:         
#            - content/appendix/project_tracking_system/project_tracking_system_considerations.qmd

format:
  html:
    toc: true
    theme:
      light: [materia, css/theme.scss]
#      dark: [materia, css/theme-dark.scss]
    mermaid:
      theme: neutral
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px
    comments:
      hypothesis: 
        theme: clean      

filters:
  - include-files.lua
  - quarto
