project: 
  type: website

language: 
  search-box-placeholder: "Search" # Currrently not working. Old version? 

website: 
  page-navigation: true
  title: "USFWS Science Applications - Metadata Guidance QUARTO" 
  site-url: "https://studious-adventure-wo15nv1.pages.github.io" 
  repo-url: "https://github.com/usfws/sciapps_metadata_guidance"
  repo-actions: [edit, source, issue]
  favicon: favicon.png
  search:
    location: sidebar
    type: textbox
  
  sidebar:
    title: "USFWS Science Applications Metadata Guidance"   
    background: "#D9E3E4"
    logo: "/assets/usfws_logo_64px_width.png"
    favicon: favicon.ico
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.fws.gov/program/science-applications
        text: "USFWS Science Applications"
      - icon: github
        href: https://github.com/usfws
        text: "USFWS Github"
    style: "floating"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - content/roles_and_responsibilities.qmd
      - content/goals_sa_data_management.qmd   
      - content/sa_science_catalog.qmd   
      - content/projects_products_contacts.qmd   
      - content/non_duplication_policy_guidance.qmd   
      - section: "Workflow"
        contents:
          - content/workflow/metadata_from_scratch.qmd
          - content/workflow/metadata_sciencebase_first.qmd          
          - content/workflow/metadata_editing_republishing.qmd          
          - content/workflow/metadata_project_tracking_system_considerations.qmd
      - content/settings.qmd           
      - section: "mdEditor Metadata File Management"
        contents:
          - content/mdeditor_metadata_file_management/metadata_format.qmd    
          - section: "Import"
            contents:
            - content/mdeditor_metadata_file_management/import_import_settings.qmd
            - content/mdeditor_metadata_file_management/import_mdjson.qmd          
            - content/mdeditor_metadata_file_management/import_sbjson.qmd          
            - content/mdeditor_metadata_file_management/import_fgdc.qmd          
          - content/mdeditor_metadata_file_management/export.qmd   
          - content/mdeditor_metadata_file_management/copy_records.qmd   
      - content/metadata_requirements_checklist.qmd  
      - content/digital_object_identifier.qmd        
      - section: "Project Entry Guidance"
        contents:
          - content/project_entry_guidance/overview_project.qmd
          - content/project_entry_guidance/main_tab_project.qmd          
          - content/project_entry_guidance/metadata_tab_project.qmd          
          - content/project_entry_guidance/keywords_tab_project.qmd          
          - content/project_entry_guidance/taxonomy_tab_project.qmd          
          - content/project_entry_guidance/extent_tab_project.qmd          
          - content/project_entry_guidance/documents_tab_project.qmd          
          - content/project_entry_guidance/funding_tab_project.qmd           
          - content/project_entry_guidance/associating_records_project.qmd          
      - section: "Product Entry Guidance"
        contents:
          - content/product_entry_guidance/overview_product.qmd
          - content/product_entry_guidance/main_tab_product.qmd          
          - content/product_entry_guidance/metadata_tab_product.qmd          
          - content/product_entry_guidance/keywords_tab_product.qmd          
          - content/product_entry_guidance/taxonomy_tab_product.qmd          
          - content/product_entry_guidance/extent_tab_product.qmd          
          - content/product_entry_guidance/lineage_tab_product.qmd   
          - content/product_entry_guidance/distribution_tab_product.qmd       
          - content/product_entry_guidance/constraints_tab_product.qmd       
          - content/product_entry_guidance/dictionaries_tab_product.qmd       
          - content/product_entry_guidance/documents_tab_product.qmd       
          - content/product_entry_guidance/associating_records_product.qmd       
      - section: "Co-Funded Project Requirements"
        contents:
          - content/cofunded_project_requirements/cofunded_projects_overview.qmd
          - content/cofunded_project_requirements/collaboration_protocol.qmd
          - section: "Sub-Project Protocol"          
            contents: 
              - content/cofunded_project_requirements/sub_project_protocol.qmd
              - content/cofunded_project_requirements/sub_project_of_fws_region_project.qmd
              - content/cofunded_project_requirements/sub_project_of_casc_project.qmd
          - section: "Co-Funded Protocol"          
            contents: 
              - content/cofunded_project_requirements/co_funded_protocol.qmd
              - content/cofunded_project_requirements/fws_co_funded_projects.qmd
              - content/cofunded_project_requirements/fws_casc_projects_products.qmd
              - content/cofunded_project_requirements/casc_responsibilites.qmd
              - content/cofunded_project_requirements/lcc_examples.qmd
      - section: "Contact Entry Guidance"
        contents:
          - content/contact_entry_guidance/contact_entry_guidance_overview.qmd
          - content/contact_entry_guidance/summary_contact_requirements.qmd
          - content/contact_entry_guidance/individual_contacts.qmd
          - content/contact_entry_guidance/organization_contacts.qmd
      - section: "Publish"
        contents:
          - content/publish/publish_overview.qmd
          - content/publish/requirements_for_publishing.qmd
          - content/publish/testing_publishing.qmd
          - content/publish/how_to_publish.qmd          
          - content/publish/re_publishing.qmd          
      - content/archiving_requirements.qmd
      - section: "Trouble-Shooting Tips"
        contents:
          - content/trouble_shooting_tips/trouble_shooting_tips_overview.qmd      
          - content/trouble_shooting_tips/qa_qc_fixes.qmd      
          - content/trouble_shooting_tips/qa_qc_resources.qmd      
      - section: "Bulk Editing Resources"
        contents:
          - content/bulk_editing_resources/injector_script_overview.qmd      
          - content/bulk_editing_resources/injector_script_funding.qmd      
          - content/bulk_editing_resources/injector_script_distribution_links.qmd 
      - content/help.qmd
      - content/glossary_of_terms.qmd

format:
  html:
    toc: true
    theme:
      light: [materia, theme.scss]
      dark: [materia, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px
      
filters:
  - include-files.lua
  - quarto

  
