---
title: "USFWS Science Applications Metadata Guidance"
subtitle: "A guide to mdEditor and ScienceBase for Science Applications"
page-layout: full
execute: 
  enabled: true
format:
  html:
    link-external-icon: false
    link-external-newwindow: true
project:
     execute-dir: project    
---

```{r, echo=FALSE}
todays_date = format(Sys.time(), '%d %B, %Y')
```

## Introduction

This manual describes the requirements and best practices for the creation of 
high-quality and consistent metadata records for projects and products for 
USFWS Science Applications (SA) Program. These metadata requirements conform to 
the standardized metadata format agreed upon by the SA Data Management Working 
Group and meet USFWS policy requirements for data management. This metadata is 
aggregated and organized in the SA Science Catalog, where SA projects and 
products are discoverable, accessible, and usable.

## USFWS Data Management Integration

Metadata is an essential element of the 
[Data Management Lifecycle](https://doimspp.sharepoint.com/sites/fws-data/SitePages/Data_management_life_cycle_home.aspx). 
Creating metadata is the principal component of the **Maintain** step. 
Publishing metadata in an approved repository (e.g., ScienceBase) is crucial
to the **Access** and **Archive** steps.

Overall guidance about USFWS Data Management is in the [USFWS Data Management Handbook](https://doimspp.sharepoint.com/sites/fws-data/Shared%20Documents/References/DataManagementHandbook.pdf?web=1).

### Metadata and mdEditor

The metadata editing tool used to create and support metadata requirements 
is mdEditor. This tool was initially developed by the 
[Alaska Data Integration Working Group (ADIwg)](http://www.adiwg.org/about/) 
and adopted by SA. The mdEditor application is under constant development. 
Consequently, there may be some minor discrepancies between screenshots in this 
guidance and the current version of mdEditor.

This manual refers to the creation of SA metadata specifically. If you want 
information on the creation of other metadata records using mdEditor, or more 
information in general, please refer to the 
[mdEditor User Manual](https:/./adiwg.gitbooks.io/mdeditor/content/).

## Who Should Use this Manual

This guide is for anyone creating or updating metadata for SA-related projects 
and products. The primary purpose is to describe in detail how to develop 
metadata for items for inclusion in the SA Science Catalog, but the tool can 
also be used to track any project or funding.

The metadata requirements described here apply to science projects and products 
that were funded by SA (for more details, see the 
[Project, Products, and Contacts](content/projects_products_contacts.qmd) section).

## How to Use this Manual

The recommended way to use this manual is directly accessing the pages from the 
internet. By doing so, you guarantee you are using the current version. This is 
a living document and will be updated as needed. The online version will 
also have the best functionality and graphical display.

This document will continue to be updated regularly and publishing using the 
[GitHub Repository](https://github.com/USFWS/Science_Applications_Metadata_Guidance). 
Please refresh 
this manual every time you open it to ensure you are viewing the most recent 
version. **Last updated:** **`r todays_date`**. 

## Providing Feedback

If you would like to provide feedback (e.g., comments, suggestions, etc.) about
this guidance, you can use this [online form](https://forms.office.com/g/xtkDZ3rQjW).  

If you’d like to give direct feedback through Github, please consider reporting 
an [issue](https://github.com/USFWS/sciapps_metadata_guidance/issues/new) 
or submitting edits through a 
[pull request](https://github.com/USFWS/sciapps_metadata_guidance). However, 
in order to access these functions, you will be required to sign in or
create an account with Github.