---
title: "data.gov Guidance"
editor: 
  markdown: 
    wrap: 80
---

Follow the guidance below for items to be sent to data.gov.

## **What products go into data.gov?**

The information below is based on the best available information about data.gov
as of April 2018. A future Department of the Interior data governance board may
issue written guidance about what is appropriate for data.gov.

-   Machine-readable, non-proprietary data sets are top priority (e.g., .csv,
    txt, etc.), including GIS files (e.g., .shp, .jpg, .tif, geotif, etc.).
-   If no machine-readable version of the data exists, then proprietary data
    formats (e.g., .mdb, .accdb, .xlxs, FGDB, etc.) may be cataloged.
-   Cataloging spatial or non-spatial data web services (OGC, WMS, WFS, etc.),
    ESRI (map services, feature services, hosted feature layers, image
    services), etc. is acceptable.
-   Data (or static maps) in the form of a .pdf file is acceptable to catalog if
    there is no other file format of of the data.
-   Data.gov is intended for data only. As such, NO publications, report
    documents, web pages, or presentation recordings are to be cataloged.

:::{.callout-warning} 
Avoid submitting a dataset more than once. If someone
else from any organization has cataloged the identical data on data.gov, do not
enter it again. 
:::

## Requirements to send something to data.gov

1.  Set the appropriate [data.gov Metadata Repository
    tag](./#metadata-repositories).
2.  List the Science Applications National Data Steward first in the list of
    [Responsible Parties](main_tab_product.qmd#citation) (#0). data.gov only
    displays the first contact and the data steward should be listed first.
3.  Include a [Distribution Link](../distribution_tab_product.qmd) where the 
    product can be accessed or downloaded.

## data.doi.gov

Items actually go through an intermediary before they harvested to data.gov. All
Department of the Interior items go through data.doi.gov first.

Link to DOI data.gov: <https://data.doi.gov/dataset>

Link to LCC Network items:
<https://data.doi.gov/dataset?organization=lcc-network>

Link to SA items: (insert link here)
