---
title: "Extent Tab: Product"
editor: 
  markdown: 
    wrap: 80
---

**Extent** refers to geographic boundaries for your project. Spatial extents lets users see at a glance the geographic footprint of your project and allows searching within specific geographic areas.

| Quick Reference: Product Extent Tab | Required? |
| :--- | :--- |
| Extent | Required |

Spatial extents should be included for all applicable products. As a default, products should inherit extents from their parent project. geoJSON files for specific geographies are available on [ScienceBase](https://www.sciencebase.gov/catalog/item/5bd7c96fe4b0b3fc5ce82d44) \(private DMWG folder that requires ScienceBase login\). Download the relevant files and then import the geoJSON files into mdEditor.

{% hint style="info" %}
Tip: You can export, save, and import an extent to use for other projects or products.
{% endhint %}

See further information on Extents in the [Project Extent entry guidance](https://github.com/tpatterson1996/lcc-metadata-manual/tree/287090b07635d0e76a714278ce1f6c4aac3594cc/record/main/extent-tab.html).

