---
title: "Trouble-Shooting: Overview"
description: "If you find an issue and have a solution to share, please contact the SA Architecture Sub-Group (ASG)."
editor: 
  markdown: 
    wrap: 80
draft: true # REMOVE if you want this page to publish    
---

```{r, echo=FALSE}
setwd("../..")
source(file.path(getwd(), "config.R"))
```

## Issues or Feedback for the Guidance

If you would like to provide feedback (e.g., comments, suggestions, etc.) about
this guidance, you can use this [online form](https://forms.office.com/g/xtkDZ3rQjW).  

If you’d like to give direct feedback through Github, please consider reporting 
an [issue](https://github.com/USFWS/sciapps_metadata_guidance/issues/new) 
or submitting edits through a 
[pull request](https://github.com/USFWS/sciapps_metadata_guidance). However, 
in order to access these functions, you will be required to sign in or
create an account with Github.

## Records fail to update to the SA Science Catalog

Occasionally, an item may seem to publish correctly to ScienceBase when if fact,
the mdJSON did not publish. ScienceBase items without mdJSON file attachments
are not in the Science Catalog. Remember that newly-published mdJSON will not be
reflected in the Science Catalog until the following day (it updates daily
overnight).
