---
title: "Collaboration Protocol"
editor: 
  markdown: 
    wrap: 80
---

## Applicability

**This protocol is applicable when**: Multiple regions, programs, etc. collaborate on a single project where only
  one region provided funding (this funding region is the lead). There can
  only be one lead region per project.

## Metadata Responsibility

The Lead Region Data Manager is responsible for project and product metadata.
There should only be one metadata record for each collaborating project and
product. These records will publish and be searchable in the Science Catalog for
each collaborating Region identified in the metadata.

::: {.callout-note icon=false}
If the project is collaborative between multiple regions but neither provides
direct funding allocations, the regions should determine who will be the lead
region and be responsible for entering the metadata.
:::

In addition to metadata requirements described in 
[Project Records](../project_records/project_records_overview.qmd), 
enter the following for projects with multiple Service Regional or Program 
collaborators:

## Funding/Other Contacts

Include the Lead Region and/or Program in other funding contacts as
**administrator** (see 
[Contact Records](../contact_records/contact_records_overview.qmd)).
