---
title: "Sub-Project of FWS Region or Program Project"
editor: 
  markdown: 
    wrap: 80
---

When a project is a sub-project (aka child project) of a larger Service project,
complete a project metadata record for the sub-project as in
[Project Records](../project_records/project_records_overview.qmd) 
with the following additions. Products of a sub-project are handled as 
described in [Product Records](../product_records/product_records_overview.qmd) 
with no additional requirements.

## Main/Points of Contact

Add the parent project region(s) or program(s) as a “collaborator”.

:::{.callout-info}
The region or program that is funding the
sub-project or distinct product is the “administrator” in the sub-project
funding metadata as described in [Funding Tab](../project_records/funding_tab_project.qmd). 
:::

## Metadata/Metadata Contacts

The default publisher is USFWS. The lead region or program may be included as
“publisher”, but this is not required. Collaborators do not need to be listed
here either.

## Associated

Associate the relevant projects, sub-projects, and products with each other in
mdEditor as described in 
[Associating Records (Project)](../project_records/associating_records_project.qmd). 
Your ownership/edit access to the related items will determine how you enter the
associations in mdEditor. Information below refers to the Associated tab.

### When you have edit rights to Parent Project

If your sub-project falls underneath a project that you also manage or have edit
rights, you can create the association by defining the association type and
linking your records as normal (see 
[Associating Records (Project)](../project_records/associating_records_project.qmd)).

In the Associated tab, add the association type as one of the following and
select the appropriate record to link:

-   As parent project to sub-project relationship: “parentProject”/”subProject”
    or vice versa
-   As parent project to product relationship: “parentProject”/“product”
-   If neither is a parent of the other, as Part of the other project:
    “isPartOf”/“isPartOf”

### When you do NOT have edit rights to Parent Project

If your sub-project falls underneath a project to which you do not have edit
rights for its ScienceBase record or mdEditor file, the metadata records will
need to be associated manually within mdEditor (or contact the metadata owner to
request assistance with creating the association.)

To create the association manually, enter the association type as described
above, enter the resource type, then copy and paste the title and ScienceBase
Identifier for the associated item (see Figure 1).

If creating associations to other regional or program items that have s SA
Science Catalog tag, then those items will show up in the Science Catalog, along
with your sub-projects and products.

:::{.callout-info} 
If your sub-project falls underneath a CASC project, refer to the next page: 
[Sub-project of CASC Project](subproject_of_casc_project.qmd). 
:::
