---
title: "ScienceBase First"
subtitle: "Metadata Workflows"
editor: 
  markdown: 
    wrap: 80
---

Follow this workflow if you are creating mdJSON for the first time and already
have project or product metadata on ScienceBase.

### 1. Gather information 

Have information about your contacts, projects, and products on hand before you
begin creating metadata records. Key information to gather includes project
proposals, funding agreements and amounts, project reports, product information,
and contact information for individuals and organizations involved in the
projects.

### 2. Open mdEditor

The direct link to mdEditor is <https://go.mdeditor.org>. Choose the browser you
plan to use for mdEditor and bookmark this link.

The [mdEditor homepage](https://www.mdeditor.org) provides some background 
information and Frequently Asked Questions about mdEditor.

Always hit ***Refresh*** in your browser before each work session (and
periodically throughout the session) to ensure that you are using the most
updated version of mdEditor.

### 3. Adjust settings

In mdEditor settings, set the SA-specific settings for importing from
ScienceBase, Metadata Repositories, and Publishing (See
[Settings](../settings.qmd)).

### 4. Create or import contacts

Contacts must be created or uploaded before they can be added to project and
product metadata records using the
[Contacts](../contact_records/contact_records_overview.qmd) entry form in
mdEditor.

SA has a "seed list" of contacts that that contains standardized information 
for common partner agencies, USFWS regions, and the SA Network Data Steward. 
This **Contacts Seed** file (as a .json) can be downloaded from the
[mdEditor Seed Contacts item page](https://www.sciencebase.gov/catalog/item/5df8d2b7e4b0cdded73b4069).
and then imported into mdEditor using the 
[Import](../metadata_file_management/import_mdjson.qmd) tab.

### 5. Import projects

For importing metadata for a
[project](../project_records/project_records_overview.qmd) of an existing 
ScienceBase project, import the ScienceBase record to create a new mdEditor 
record using the [sbJSON Import](../metadata_file_management/import_sbjson.qmd).

### 6. Import products

For importing metadata for a
[product](../product_records/product_records_overview.qmd) of an existing 
ScienceBase product record, import the ScienceBase record to create a new 
mdEditor record using the [sbJSON Import](../metadata_file_management/import_sbjson.qmd).

### 7. Create or import data dictionaries

If a product record have a need for data
[dictionaries](../product_records/dictionaries_tab_product.qmd), create or
import one.

### 8. Complete metadata

Decide on your desired file management approach and complete your metadata
accordingly. See the [File Management](../metadata_file_management/metadata_file_management_overview.qmd)
section for options and instructions.

### 9. Create associations

For projects and/or products, associations can be either [associated from a
project](../project_records/associated_tab_project.qmd) or [associated from
a product](../product_records/associated_tab_product.qmd).

### 10. Publish your records

From the mdEditor interface, [publish](../publishing/publishing_overview.qmd)
the records to ScienceBase.

### 11. Export your records

Use the [Export](../metadata_file_management/export.qmd) function to export
records of your products, projects, and contacts for backup, transfer, or
sharing. You may want to export working backups before publishing depending on
your situation, but archival exports should be done after publishing since
publishing can alter records, like adding or changing a ScienceBase ID.

### 12. Review Science Catalog

The [SA Science Catalog](https://www.fws.gov/science/catalog/) updates overnight
so you should review newly-published records the day after you publish to
ScienceBase. This will be one of your best quality control checks.

