---
title: "Co-Funded LCC Projects"
editor: 
  markdown: 
    wrap: 80
---

The following are real examples of past LCC and CASC co-funded projects and
products. The links go directly to the ScienceBase records so you can download
their mdJSON to explore how these were done.

## Example: Gulf Coast Prairie LCC / Gulf Coastal Plains and Ozarks LCC / South Central CASC

### Project Record

Title: Occurrence and variation in submersed aquatic vegetation (SAV) along the
northern Gulf of Mexico: a hierarchical approach to assess impacts of
environmental change on SAV resources

-   LCC item:
    <https://www.sciencebase.gov/catalog/item/587e5cd5e4b0a765aab5ebab>
-   CASC item:
    <https://www.sciencebase.gov/catalog/item/5012df8ce4b05140039e03c7>

### Product Record

Title: Sediment carbon, submerged aquatic vegetation and environmental variables
in deltaic southeast Louisiana (2015-2016)

-   LCC item:
    <https://www.sciencebase.gov/catalog/item/5a78be62e4b00f54eb1e849c>
-   CASC item:
    <https://www.sciencebase.gov/catalog/item/5887c1c3e4b02e34393da82d>

## Example: Upper Midwest and Great Lakes LCC / Northeast CASC

### Project Record

Title: Understanding How Climate Change will Impact Aquatic Food Webs in the
Great Lakes

-   LCC item:
    <https://www.sciencebase.gov/catalog/item/59fb44f5e4b0531197b16290>
-   CASC item:
    <https://www.sciencebase.gov/catalog/item/500708cee4b0abf7ce733ff1>
