---
title: "LCC Workflows - Overview"
order: 1
editor: 
  markdown: 
    wrap: 80
---

Science Applications originally coordinated the Landscape Conservation
Cooperatives --- a network of individual, geographically distinct partnerships. 
The 22 Landscape Conservation Cooperatives (LCCs) developed
uniquely and independently based on the needs of their regions and partnerships.
As a result, there was not a single workflow for data management and sharing
among the LCCs. Instead there were multiple workflows, varying formats, and
different use cases for managing and sharing the results of LCC-funded projects.
Further, because LCCs placed varying levels of importance on data management,
LCCs varied greatly in their staff capacity for data management.

While the individual workflows met the needs of the individual LCCs and their
partner organizations, they were not enough to achieve the goal of a
network-wide, integrated dynamic project and product database. Through
collective agreement, LCCs agreed they needed to modify their workflows to
create comparable project and product metadata.

Procedurally, the LCC Network has committed to using ScienceBase for cataloging
all funded projects and associated products. As per the LCC Network’s response
to a DOI Office of the Inspector General 2017 report, individual LCCs were
required to contribute their project and product metadata to the ScienceBase
repository by the end of 2017 and mid-2018 respectively. In tandem with this
ScienceBase requirement, the LCC Network was required to post data products to
Data.gov and this data conduit be in place with products cataloged by end of
2018.

While SA has refocused on FWS priorities, the need for data management,
integration, and sharing process remains essential to mission of FWS and SA.
This guidance was developed by the SA Data Management Working Group (DMWG) with
the leadership of the Architecture Subgroup (ASG).