---
editor: 
  markdown: 
    wrap: 80

description: Describes FWS Enterprise Roles and defines Responsibilities within SA
---

# Roles & Responsibilities (Draft)

### ARDs

Definition​: Assistant Regional Directors for Science Applications

-   Responsible for supporting staff time and allocating resources to follow
    the SA Data Management Plan through their entire chain of command
-   Ensure data management responsibilities are followed when SA funds go are
    allocated outside the program (e.g., to another FWS program)
-   Ensure Performance Appraisal Plans reflect responsibilities for data
    stewardship
-   Sign ​memo​ stating a project intended for funding is not duplicative
    research or other science activity (Science Project) and therefore does
    not need to go through any additional steps in the [SA Non-Duplication
    Policy](policy-guidance.md).
-   Sign ​CASC Consultation Certification memo​ stating the CASC consultation
    took place and identified not duplication of funding between SA and a
    CASC. For grants and cooperative agreements, this can be certified by
    checking the appropriate check box on the Award Checklist - FWS Form
    3-2460.

### AD and Deputy AD

Definition​: Assistant Director and Deputy Assistant Director for Science
Applications

-   Provide program leadership and accountability to ensure all SA data
    management, Science Catalog, internal tracking, and non-duplication
    policies are followed across the program.
-   Ensure data management responsibilities are followed when SA funds go
    outside the program (e.g., to another FWS program)

### HQ Staff

Definition​: Science Applications HQ staff who are responsible for coordinating
and leading SA data management efforts, including but not limited to: SA HQ
Science Coordinators and the SA HQ Grants Manager.

-   Ensure data management responsibilities are followed when SA funds go
    outside the program (e.g., to another FWS program)
-   Create CASC consultation Google Form to be sent to CASC director(s)

### SA Contracting Officer

Definition​: SA staff who serve as Contracting officials and Contracting Office
Representatives and \*\*\*\*are the primary liaison with the contracting
personnel who issue and administer contracts.

-   Work with SA Project Officer to ensure that all data procurement contracts
    and agreements make appropriate reference to data management and, at a
    minimum, define the general data management requirements within every
    contract and agreement.

### SA Grants Manager

Definition​: SA staff who are responsible for issuing financial assistance
awards or who are the primary liaison(s) with WSFR staff who issue financial
assistance awards.

-   Work with SA Project Officer to ensure that all data procurement
    agreements make appropriate reference to data management and, at a
    minimum, define the general data management requirements within every
    agreement.

### SA Project Officer

Definition​: SA personnel responsible for administering grants and cooperative
agreements, reviewing and selecting proposals, reviewing and approving interim
and final reports, and ensuring receipt of deliverables.

-   Ensure SA data management, Science Catalog, internal tracking, and
    non-duplication policies and requirements are followed for the projects
    they manage. This can be done themselves, requiring the work from PIs
    (e.g. product metadata), or delegating the work to a data manager/steward
    -   Include requirement for data management plan
    -   Include requirements for project and product metadata
    -   Ensure the project record is posted to ScienceBase within 30 days
    -   Ensure the full metadata is updated
-   Ensure scope of work contains requirements for metadata and data
    management plan deliverables.
-   Ensure all Non-duplication documentation (memos, SB searches) are added to
    award file.

### Non-SA Project Officer

Definition​: Non-SA staff (still FWS) who serve as the Project Officer on
agreements using SA funds.

-   Ensure scope of work contains requirements for metadata and data
    management plan deliverables.
-   Ensure all Non-duplication documentation (memos, SB searches) are added to
    award file.
-   Work with SA Data Steward/ARD to ensure that all SA data management,
    Science Catalog, internal tracking, and non-duplication policies and
    requirements are followed.

### Non-SA Principal Investigator

Definition​: An externally-funded recipient of SA funds via grant, cooperative
agreement, contract, or inter-agency agreement, who is responsible for leading
the funded project and providing deliverables to SA.

-   Transfer deliverables to SA Project Officer
-   Write and transfer metadata to SA Project Officer
-   Works with Data Steward to develop a Data Management Plan

### SA Principal Investigator

Definition​: SA staff who is responsible for leading the internal project who
also assumes the roleof Project Officer.

-   Assumes role of SA Project Officer

-   Ensures deliverables are loaded to ScienceBase

-   Write/ ensures project and product metadata meets SA standards

-   Works with Data Steward to develop a Data Management Plan

### Data Steward

Definition​: Any SA staff or personnel working on behalf of SA (e.g.,
contractor) who performs a data management action - writing, reviewing, or
publishing metadata; publishing deliverables; etc. Can be project officer,
data manager, or other staff. Often a Data manager fills this role.

-   Assist non-SA Project Officers with ensuring SA data management, Science
    Catalog, internal tracking, and non-duplication policies and requirements
    are followed.

### Science Coordinators
