---
editor: 
  markdown: 
    wrap: 80
---

# Projects, Products, Contacts

## Understanding Projects, Products, and Contacts

Contacts, projects, and products all share a relationship in mdEditor and are
each entered independently.

### Projects

A project encompasses a discrete effort on a particular topic with defined goals
or objectives. The target projects for the SA Science Catalog are science
projects whose topics and resulting products have value to partners or the
public being able to discover and access them. Many projects are the result of
SA issued financial assistance agreements, contracts, or inter-agency
agreements. However, not everything funded through one of these mechanisms needs
to be in the Science Catalog. For example, a contract to maintain an individual
website likely does not quality as a "science project" nor does it provide
public-relevant information. A grant to develop an interactive
landscape-conservation tool, however, would be a science project that results in
public-relevant information.

SA projects can also include other defined efforts that did not necessarily
require the awarding of funds (i.e. internal efforts).

::: callout-note
Individual data managers may want to track other projects using the same
metadata format and store that information on ScienceBase, without publishing it
to the SA Science Catalog.
:::

### Products

A product is a resource, usually (but not necessarily) developed as an output
from a project. Products can be tools, data, maps, reports, presentations,
workshops, etc. These will usually be the direct result of a project though
there may be some products without a parent project.

Not every output of a project is necessarily a product, however. For example,
meeting minutes do not have standalone value as a publicly-available resource.
It is up to each data manager to determine which outputs should be entered as
products.

### Contacts

Contacts are the individuals and organizations involved with projects and
products (e.g., investigators, collaborators, funders). Contacts are entered
once in mdEditor and can be added to multiple projects and products.

::: callout-note
Consult the [Contacts](contacts/) section for information on adding contacts.
:::

### Relationships

**Projects and Products** will always have a relationship with contacts.
Projects will always have at least one point of contact (FWS SA National Data
Steward). Additional contact relationships may include project authors, metadata
creators, funders, principal investigators, publishers, distributors, and many
others. One crucial contact relationship between contacts, projects, and
products is the role of the individual(s) and/or organization(s) who provided
funding. This may include a direct full contributor or any partners that
provided funding.

::: callout-note
Contact types are specified in the contact record (examples: federal, state,
NGO). Specific roles for each contact are defined within the respective project
and product records (examples: principal investigator, collaborator).
:::

**Products are often the results of projects**. mdEditor defines the
relationships between projects and products through the Associated feature.

::: callout-note
Consult either the [Associating Records:
Product](product-entry-guidance/associating-records-products.md) or [Associating
Records: Project](project-entry-guidance/associating-records.md) section for
more information).
:::
