---
editor: 
  markdown: 
    wrap: 80
---

# Metadata From Scratch

Follow this workflow if you are creating mdJSON metadata for the very first time
and you do not have existing project or product metadata already on ScienceBase.

## Step 1: Gather information needed for your metadata entries.

Have information about your contacts, projects, and products on hand before you
begin creating metadata records. Key information to gather includes project
proposals, funding agreements and amounts, project reports, product information,
and contact information for individuals and organizations involved in the
projects.

Use the "contacts seed file" that contains pre-filled information and standard
naming conventions for all SA regions, common federal agencies, and the SA
National Data Steward.

## Step 2: Open mdEditor.

The direct link to mdEditor is <https://go.mdeditor.org>. Choose the browser you
plan to use for mdEditor and bookmark this link.

mdEditor can also be accessed from its homepage at <https://www.mdeditor.org/>.
This site provides some background information and Frequently Asked Questions
about mdEditor.

## Step 3: Set the correct default [Settings](../settings.md).

In mdEditor settings, set the SA-specific settings for Importing, Metadata
Repositories, and Publishing.

## Step 4: Create [Contacts](../contacts/).

Contacts must be created or uploaded before they can be added to project and
product metadata records.

## Step 5: Create [Projects](../project-entry-guidance/).

If you have an existing ScienceBase project record that has not been edited in
mdEditor, import the ScienceBase record to create a new mdEditor record.

If you have no existing metadata for a project, create an mdEditor project
record from scratch.

If you have already created an mdEditor record for the project, import the
mdEditor file to continue editing.

## Step 6: Create [Products](../product-entry-guidance/).

If you have an existing ScienceBase product record that has not been edited in
mdEditor, import the ScienceBase record to create a new mdEditor record.

If you have no existing metadata for a product, create an mdEditor product
record from scratch.

If you have already created an mdEditor record for the product, import the
mdEditor file to continue editing.

## Step 7: For applicable Products, create Data [Dictionaries](../product-entry-guidance/dictionaries-tab-product.md).

## Step 8: Complete metadata.

Decide on your desired file management approach and complete your metadata
accordingly. See the [File Management](../data-management/) section for options
and instructions.

## Step 9: Create desired Associations between Projects and/or Products.

Associations can be either [associated from a
project](../project-entry-guidance/associating-records.md)or [associated from a
product.](../product-entry-guidance/associating-records-products.md)

## Step 10: [Publish](../publish/) your records to ScienceBase.

## Step 11: [Export](../data-management/export.md) your records and contacts for backup, transfer, or sharing.

You may want to export working backups before publishing depending on your
situation, but archival exports should be done after publishing since publishing
can alter records, like adding or changing a ScienceBase ID.

## Step 12: Review the resulting entries in the [SA Science Catalog](https://www.fws.gov/science/catalog/).

The Science Catalog updates overnight so you should review newly-published
records the day after you publish to ScienceBase. This will be one of your best
quality control checks.
