---
title: "Data Management Goals"
subtitle: "Science Applications Program"
editor: 
  markdown: 
    wrap: 80
---

The original goal of Science Applications data management efforts were to create
an integrated project and product database for the Landscape Conservation
Cooperatives (LCCs). After the conclusion of the LCCs, much of that 
workflow is applicable for general SA metadata management.

As SA has refocused on broader FWS priorities, the need for data management,
integration, and sharing process remains essential to mission of USFWS and 
SA. This guidance was developed by the SA Data Management Working Group (DMWG) 
with the leadership of the Architecture Subgroup (ASG).

## Science Catalog Goals and Objectives

### Goal 1: Searchable Repository

##### Provide an easily searchable repository for SA-funded science projects and products through the SA Science Catalog.

<p style="margin-top:.5cm;margin-bottom:0cm">

</p>

[Objectives]{.underline}

1.  Enable efficient and consistent searching and filtering across all SA
    projects and product.

2.  Ensure resource managers and partners can continue to find and use SA
    information and products for decision-making and conservation action on the
    landscape.

3.  Support users (e.g., resource managers, scientists, auditors, graduate
    students) in identifying remaining/future science needs and preventing
    future duplication of work by displaying who and what SA has funded.

4.  Ensure the SA Science Catalog instance will remain accessible through a
    portable design that can be hosted on fws.gov and elsewhere, if needed.

--------------------------------------------------------------------------------

### Goal 2: Increase Transparency

##### Increase transparency of SA project funding information.

<p style="margin-top:.5cm;margin-bottom:0cm">

</p>

[Objectives]{.underline}

1.  Document how FWS and other sources of funding were used to fund science
    projects.

2.  Enable Science Applications and other key partners to show how FWS and other
    sources of funding were allocated to partners (e.g., states, tribes, federal
    agencies).

3.  Allow data managers to use the Science Catalog as an internal project
    tracking system.

--------------------------------------------------------------------------------

### Goal 3: Demonstrate Investment

##### Demonstrate the impact and value of the investment in landscape-scale conservation.

<p style="margin-top:.5cm;margin-bottom:0cm">

</p>

[Objectives]{.underline}

1.  Enable Science Applications and other key partners to show how investments
    by FWS and other federal programs leveraged additional funding by partners.

2.  Demonstrate the depth and breadth of the projects and products produced by
    SA and the partners and collaborators involved.

--------------------------------------------------------------------------------

### Goal 4: Link Science to Conservation

##### Illustrate the link between SA-funded applied science projects and today’s conservation challenges.

<p style="margin-top:.5cm;margin-bottom:0cm">

</p>

[Objectives]{.underline}

1.  Link SA projects and products to overarching Conservation Issues.
