# Goals of SA Data Management

> We envision a well-functioning data management, integration, and sharing process that integrates, at minimum, the products of SA-funded projects with those from regionally-funded projects, and that support the data lifecycle in a coordinated manner.—Conservation Science Plan v.1

In the beginning, Science Applications was leading the Landscape Conservation Cooperatives:  A network of individual, geographically distinct partnerships coordinated by SA.  The 22 Landscape Conservation Cooperatives \(LCCs\) developed uniquely and independently based on the needs of their regions and partnerships. As a result, there was not a single workflow for data management and sharing among the LCCs. Instead there were multiple workflows, varying formats, and different use cases for managing and sharing the results of LCC-funded projects. Further, because LCCs placed varying levels of importance on data management, LCCs varied greatly in their staff capacity for data management.

While the individual workflows met the needs of the individual LCCs and their partner organizations, they were not enough to achieve the goal of a network-wide, integrated dynamic project and product database. Through collective agreement, LCCs agreed they needed to modify their workflows to create comparable project and product metadata.

Procedurally, the LCC Network has committed to using ScienceBase for cataloging all funded projects and associated products. As per the LCC Network’s response to a DOI Office of the Inspector General 2017 report, individual LCCs must contribute their project and product metadata to the ScienceBase repository by the end of 2017 and mid-2018 respectively. In tandem with this ScienceBase requirement, the LCC Network is required to post data products to data.gov and this data conduit will be in place with products cataloged by end of 2018.

While SA has refocused on FWS priorities, the need for data management, integration, and sharing process remains essential to mission of FWS and SA. This guidance was developed by the SA Data Management Working Group \(DMWG\) with the leadership of the Architecture Subgroup \(ASG\).

## Science Catalog Goals and Objectives

### Goal 1: Provide an easily searchable repository for SA-funded science projects and products through the SA Science Catalog.

Objective 1.1: Enable efficient and consistent searching and filtering across all SA projects and products&gt;

Objective 1.2: Ensure resource managers and partners can continue to find and use LCC information and products for decision-making and conservation action on the landscape.

Objective 1.3: Support users \(e.g., resource managers, scientists, auditors, graduate students\) in identifying remaining/future science needs and preventing future duplication of work by displaying who and what SA has funded.

Objective 1.4: Ensure the SA Science Catalog instance will remain accessible through a portable design that can be hosted on fws.gov and elsewhere, if needed.

### Goal 2: Increase transparency of SA project funding information.

Objective 2.1: Document how FWS and other sources of funding were used to fund science projects.

Objective 2.2: Enable Science Applications and other key partners to show how FWS and other sources of funding were allocated to partners \(e.g., states, tribes, federal agencies\).

Objective 2.3: Allow data managers to use the Science Catalog as an internal project tracking system.

### Goal 3: Demonstrate the impact and value of the investment in landscape-scale conservation.

Objective 3.1: Enable Science Applications and other key partners to show how investments by FWS and other federal programs leveraged additional funding by partners.

Objective 3.2: Demonstrate the depth and breadth of the projects and products produced by SA and the partners and collaborators involved.

### Goal 4: Illustrate the link between SA-funded applied science projects and today’s conservation challenges.

Objective 4.1: Link SA projects and products to overarching Conservation Issues.

