---
title: "Non-Duplication Policy"
order: 5
editor: 
  markdown: 
    wrap: 80
---

Based on a 2017 OIG audit, minimal metadata fields are required to be published
within 30-days of project funding. The purpose of this policy is to share
information with partners regarding what science projects SA is supporting. This
transparency helps to reduce duplication of efforts across funding agencies and
allows partners to discover and engage in SA supported science as desired.

| Quick Reference: Project metadata for Non Duplication Policy                               | Required |
|:---------------------------------------|:---------------------------------------|
| Basic Information: Title, Status                                                           | Required |
| Point of Contacts (see [Main Tab](project_records/main_tab_project.qmd#point-of-contacts)) | Required |
| Description: Abstract                                                                      | Required |
| Time Period                                                                                | Required |
| Funding: Award Number, amount, source, fiscal year, recipients                             | Required |
: {.striped .hover .bordered .md .allborder} 

Below is a copy of the Non Duplication Policy guidance memo, in detail for
reference:

### Guidance for Preventing Duplication of Research and Other Science Activities

#### Background

On September 1, 2017, and December 7, 2017, the U.S. Fish and Wildlife Service
(Service) issued memos detailing actions all Assistant Regional Directors,
Science Applications (SA-ARDs), must take to prevent duplication of research
across Science Applications and United States Geological Survey Climate
Adaptation Science Centers (CASCs). This document provides further guidance for
how to best comply with those memos, in addition to other measures that can be
undertaken to prevent duplicative research across Science Applications, CASCs,
and other federal programs. See this [Non-Duplication Policies
Dashboard](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/Shared%20Documents/NonDuplication%20Policy%20Resources/READ%20ME%20FIRST.docx?d=wbbecf1f040af46c892c2246b50f327cb&csf=1&e=xoY6en)
for a list of resources.

#### Summary of Required Actions

For all financial assistance and inter- or intra-agency agreements or contracts
for research projects and other science activities you must do what is outlined
in the list below. Unless otherwise specified, the following applies to all
science projects funded with SA applications monies (1410, 1420, and 1430):

1.  First determine if the project is a research project or other science
    activity. Consider whether the project will result in a science product
    (e.g. survey, study, tool, assessment, publication, etc.).

    a.  If you decide that it **is not** **research** or another type of other
        science activity, document your decision using [this
        template](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/_layouts/15/Doc.aspx?sourcedoc=%7BCBE94F78-67C1-478F-9A3A-DD264F031155%7D&file=SA_nonDup_policy_notScienceActivity_note_to_file_template_v2.docx&action=default&mobileredirect=true)
        and attach it to the official award file.

    b.  If you decide that it **is** **research** or another type of science
        activity, proceed with the steps outlined below.

2.  Search for duplicative projects in ScienceBase (use the [ScienceBase search
    template](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/Shared%20Documents/NonDuplication%20Policy%20Resources/All%20Other%20SA%20NonDuplication%20Policy%20Documents/Search%20Documentation%20Template_clean.docx?d=wfec340115ba14373b7cd9ecb92e309ac&csf=1&e=dyVjxv)).

3.  Add this language to the NOFO: “Applicants must document literature searches
    (e.g. academic literature, industry publication, ScienceBase, and Data.gov).
    Applicants should explain why their project is non-duplicative and how it
    will augment existing knowledge.”

4.  Include peer review as part of project selection.

5.  You must document consultation with the appropriate CASC director(s). Send
    an email to Anna-Marie York
    ([Anna-Marie_York\@fws.gov](mailto:Anna-Marie_York@fws.gov)) to obtain an
    electronic form to document consultation with CASC directors. The form link
    can be shared with anyone in the Department of the Interior and offers the
    ability to create a spreadsheet that summarizes responses, including a time
    stamp for when each respondent completed the form.

6.  After consultation with CASCs is complete, the SA-ARD must provide a memo to
    the file ([template
    here](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/_layouts/15/Doc.aspx?sourcedoc=%7B4C2AA4BE-8EE4-4ACB-A8F9-CAA911CEDA06%7D&file=SA_nonDup_policy_consultation_note_to_file_template_v2.docx&action=default&mobileredirect=true))
    certifying that consultation occurred. (Note: for grants and cooperative
    agreements the ARD may instead certify consultation was done by checking the
    appropriate box and signing the New Award Checklist - FWS Form 3-2460).
    Include a copy of the spreadsheet of responses as part of the official award
    file.

7.  Enter all project information into ScienceBase as soon as possible, but
    within 30 days of the agreement being in place (required per [September 2017
    memo](https://doimspp.sharepoint.com/sites/NationalScienceApplicationsTeam/Shared%20Documents/General/Financial%20Resources/Non-duplication%20Policies/All%20Other%20SA%20NonDuplication%20Policy%20Documents/ClimateEffectsPrograms_042017_Public.pdf?CT=1586191476056&OR=ItemsView)).
    Provide as much information about projects as possible and update regularly,
    including adding entries for products within 30 days of receipt. See the
    ScienceBase Guidance section below for further details.

#### Required and Recommended Practices

As denoted by “(**required**)” in the list below, only practices 3, 6, and 7 are
required per policy; the others are recommended but are not required. Note:
required actions are the same as those listed above in the Summary of Required
Actions. Unless otherwise specified, the following applies to all science
projects funded with SA applications monies (1410, 1420, and 1430).

1.  Determine if the project is a research project or other science activity
    (required). Consider whether the project will result in a science product
    (e.g. survey, study, tool, assessment, publication, etc.).
    a.  If you decide that it IS NOT research or another type of other science
        activity, document your decision using [this
        template](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/_layouts/15/Doc.aspx?sourcedoc=%7BCBE94F78-67C1-478F-9A3A-DD264F031155%7D&file=SA_nonDup_policy_notScienceActivity_note_to_file_template_v2.docx&action=default&mobileredirect=true)
        and attach it to the official award file (required).

    b.  If you decide that it IS research or another type of science activity,
        proceed with the steps outlined below.

<!-- -->

2.  Consider coordinating with other federal agencies prior to the project
    funding phase:

    a.  You may consult informally during project development, or, when
        appropriate, invite staff from CASCs and other federal programs to be
        peer reviewers.

    b.  When invited and able, consider participating in the project development
        and selection phases for other agencies’ research programs.

3.  Search ScienceBase.gov for potentially duplicative projects prior to funding
    (**required**):

    a.  Document your search of ScienceBase using the [ScienceBase search
        template](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/Shared%20Documents/NonDuplication%20Policy%20Resources/All%20Other%20SA%20NonDuplication%20Policy%20Documents/Search%20Documentation%20Template_clean.docx?d=wfec340115ba14373b7cd9ecb92e309ac&csf=1&e=dyVjxv).

    b.  Do multiple searches (i.e. varying search terms and criteria) as
        necessary.

    c.  Be expansive in your search – use a variety of search terms and limit
        the scope only as necessary. You should not limit your search to CASC
        communities.

4.  Include copies of [ScienceBase search
    template](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/Shared%20Documents/NonDuplication%20Policy%20Resources/All%20Other%20SA%20NonDuplication%20Policy%20Documents/Search%20Documentation%20Template_clean.docx?d=wfec340115ba14373b7cd9ecb92e309ac&csf=1&e=dyVjxv)
    and corresponding results (spreadsheet) in the financial award file.

5.  Repeat Practice 2 at <https://catalog.data.gov> and any other relevant
    federal databases. You can use the [ScienceBase search
    template](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/Shared%20Documents/NonDuplication%20Policy%20Resources/All%20Other%20SA%20NonDuplication%20Policy%20Documents/Search%20Documentation%20Template_clean.docx?d=wfec340115ba14373b7cd9ecb92e309ac&csf=1&e=dyVjxv)
    to document these searches, though note that some of the instructions on the
    template are specific to ScienceBase.

6.  Insert this language in NOFO: “Applicants must document literature searchers
    (e.g. academic literature, industry publication, ScienceBase, and Data.gov).
    Applicants should explain why their project is non-duplicative and how it
    will augment existing knowledge.” (**required**)

7.  Consult with CASCs once you have selected a project to fund, but prior to
    funding. Email Anna-Marie_York\@fws.gov to obtain a link to a form to send
    to CASC directors (**required**).

    a.  Use the results of ScienceBase searches, informal consultations, and/or
        serving on review panels to identify CASCs that have funded similar
        research. You may also consider any CASC in your project geography. Aim
        to be expansive.

    b.  Consider sending the form to leadership from other federal agencies as
        well.

    c.  Using google forms will allow us to download a spreadsheet of
        time-stamped responses. Email
        [Anna_Marie_York\@fws.gov](mailto:Anna-Marie_York@fws.gov) for a copy of
        the resulting spreadsheet.

    d.  Include a copy of the responses (spreadsheet) in the financial award
        file.

8.  After consultation with CASCs is complete, the SA-ARD must provide a memo to
    the file ([template
    here](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/_layouts/15/Doc.aspx?sourcedoc=%7B4C2AA4BE-8EE4-4ACB-A8F9-CAA911CEDA06%7D&file=SA_nonDup_policy_consultation_note_to_file_template_v2.docx&action=default&mobileredirect=true))
    certifying that consultation occurred. (Note: for grants and cooperative
    agreements the ARD may instead certify consultation was done by checking the
    appropriate box and signing the New Award Checklist - FWS Form 3-2460).
    Include a copy of the spreadsheet of responses as part of the official award
    file.

9.  Enter all project information into ScienceBase as soon as possible, but
    within 30 days of the agreement being in place (required per [September 2017
    memo](https://doimspp.sharepoint.com/sites/NationalScienceApplicationsTeam/Shared%20Documents/General/Financial%20Resources/Non-duplication%20Policies/All%20Other%20SA%20NonDuplication%20Policy%20Documents/ClimateEffectsPrograms_042017_Public.pdf?CT=1586191476056&OR=ItemsView)).
    Provide as much information about projects as possible and update regularly,
    including adding entries for products within 30 days of receipt. See the
    ScienceBase Guidance section below for further details.

#### ScienceBase Guidance

1.  [Every region has folders in
    ScienceBase](https://www.sciencebase.gov/catalog/item/5b4e1c3fe4b06a6dd17df2d3)
    to put basic information about the science projects you have funded since
    September 30, 2017; per policy this is required within 30 days of funding a
    project or receiving a product. Here is what’s required for each
    project/product:

    a.  Title
    b.  PI/Funding Recipient’s[^1] Name and Contact info
    c.  PI/Funding Recipient’s Organization
    d.  Start Date
    e.  Projected End Date
    f.  Abstract
    g.  Award ID
    h.  Funding Sources and Amounts

2.  You can use mdEditor to make the records if that is your preference, or do
    it directly in ScienceBase. Here is a [video
    tutorial](https://doimspp.sharepoint.com/sites/NationalScienceApplicationsTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FNationalScienceApplicationsTeam%2FShared%20Documents%2FGeneral%2FFinancial%20Resources%2FNon%2Dduplication%20Policies%2FAll%20Other%20SA%20NonDuplication%20Policy%20Documents%2FEnterScienceProjectsOnScienceBase%2Emp4&parent=%2Fsites%2FNationalScienceApplicationsTeam%2FShared%20Documents%2FGeneral%2FFinancial%20Resources%2FNon%2Dduplication%20Policies%2FAll%20Other%20SA%20NonDuplication%20Policy%20Documents)
    showing how to enter directly on ScienceBase.

3.  If you have a science activity that more than one FWS region contributed
    funds to, but there was a “lead region” that actually administered a single
    financial award / contract, then that lead region should create and maintain
    a single record in ScienceBase for the project and its products. The project
    record should list the total amount of Service funds in the financial /
    award contract (i.e., all regions combined).

4.  If you have a science activity with multiple financial awards / contracts,
    then each award / contract should have its own ScienceBase record (note:
    modifications ARE NOT considered new awards / contracts). Whichever region
    administered each financial award / contract should create and maintain
    project and product records in ScienceBase. Please include the ScienceBase
    URL(s) for the related projects in the abstract. Example language: “this
    project is part of a larger initiative; you can find related records here:
    URL 1, URL 2, …”).

5.  If you need “editing” access to your Region’s [ScienceBase
    folder](https://www.sciencebase.gov/catalog/item/5b4e1c3fe4b06a6dd17df2d3)
    email Jill Cohen ([jillian_cohen\@fws.gov](mailto:jillian_cohen@fws.gov)).

6.  If you want a little more detail about what the “ScienceBase” policy is
    start with [slides from a
    presentation](https://doimspp.sharepoint.com/:p:/r/sites/NationalScienceApplicationsTeam/Shared%20Documents/NonDuplication%20Policy%20Resources/All%20Other%20SA%20NonDuplication%20Policy%20Documents/Presentations%20and%20webinars/Non-duplication%20for%20data%20managers.pptx?d=wea644bccaf384d4e8fa6e0bfc5b8553d&csf=1&e=e8Ppoe)
    Jill gave to the Data Management Working Group August 2018.

7.  If you want all the details about the non-duplication policies. [This
    dashboard](https://doimspp.sharepoint.com/:w:/r/sites/NationalScienceApplicationsTeam/Shared%20Documents/NonDuplication%20Policy%20Resources/READ%20ME%20FIRST.docx?d=wbbecf1f040af46c892c2246b50f327cb&csf=1&e=xoY6en)
    is your gateway.

8.  If you read through the slides and other documents and still have questions,
    or just want to check to make sure you’re doing things right call or email
    Jill Cohen ([jillian_cohen\@fws.gov](mailto:jillian_cohen@fws.gov);
    703-358-1764).

[^1]: The memo itself uses the term "project leader" instead of PI/funding
    recipient.
