---
title: "SA Science Catalog"
subtitle: "Science Applications Program"
editor: 
  markdown: 
    wrap: 80
---

A more detailed look at the metadata requirements and architecture behind the
Science Applications Science Catalog.

## Overview

The [Science Application Science Catalog](https://www.fws.gov/science/catalog)
collates the metadata from all FWS regions and Headquarters. It allows users to 
search for and filter projects and products and download products. Users can 
see what has been funded, which can help prevent duplication of work. The SA 
Science Catalog also enables reporting, such as funding summaries or project 
examples based on particular geographies, species, organization, year, or other 
categories of interest.

## SA Science Catalog and mdEditor

This sections shows the elements in the SA Science Catalog and where they are
derived in mdEditor. Items will only show up in SA Science Catalog when they 
have the proper metadata repositories designation
([Projects](project_records/metadata_tab_project.qmd#metadata-repositories) and
[Products](product_records/metadata_tab_product.qmd#metadata-repositories)) and 
have been published to ScienceBase.

### SA Science Catalog and mdEditor Fields Crosswalk Table
| SA Science Catalog      | mdEditor Project Item      | mdEditor Product Item  | 
|:---------------------|:-------------------|:-------------------|
| **Resource Type**    | [Main Tab: Resource Type](project_records/main_tab_project.qmd#resource-types-required) | [Main Tab: Resource Type](product_records/main_tab_product.qmd#resource-types-required) |
| **Title**                    | [Main Tab: Title](project_records/main_tab_project.qmd#title-required)                  | [Main Tab: Title](product_records/main_tab_product.qmd#title-required)                  |
| **Source**                   | ScienceBase folder location^**1**^ | ScienceBase folder location^**1**^ |
| **Fiscal Years Funded**      | [Funding Tab: Allocation: Time Period: Dates](project_records/funding_tab_project.qmd#dates-required) | [Associated Project](product_records/associated_tab_product.qmd)^**2**^ |
| **Last Update Date**         | [Main Tab: Citation: Dates](project_records/main_tab_project.qmd#dates-required)   | [Main Tab: Citation: Dates](product_records/main_tab_product.qmd#dates-required)  |
| **Status**                   | [Main Tab: Status](project_records/main_tab_project.qmd#status-required) | [Main Tab: Status](product_records/main_tab_product.qmd#status-required) | 
| **Project Dates (multiple)** | [Main Tab: Citation: Dates](project_records/main_tab_project.qmd#dates-required)   | [Main Tab: Citation: Dates](product_records/main_tab_product.qmd#dates-required)  |
| **Keywords**                 | [Keywords Tab](project_records/keywords_tab_project.qmd) | [Keywords Tab](product_records/keywords_tab_product.qmd)  |
| **Contacts**                 | [Main Tab: Points of Contact](project_records/main_tab_project.qmd#points-of-contact-required) | [Contacts](product_records/main_tab_product.qmd#points-of-contact-required)|
| **Funding**                  | [Funding Tab: Allocation](project_records/funding_tab_project.qmd#funding-allocation) |    |
| **Taxonomy**                 | [Taxonomy Tab](project_records/taxonomy_tab_project.qmd#add-taxonomic-system) | [Taxonomy Tab](product_records/taxonomy_tab_product.qmd#add-taxonomic-system)|
: {.striped .hover .bordered .sm .allborder} 

::: {style="font-size: 80%;"}
^**1**^ Items in ScienceBase's [USFWS Community](https://www.sciencebase.gov/catalog/item/5011a6bae4b0d78fd4e59bcd) 
are designated as "FWS ScienceBase Community". 
Items in ScienceBase's [LCC Community](https://www.sciencebase.gov/catalog/item/4f4e476ee4b07f02db47e164) are designated based 
on their top-level [Science Applications Region](https://www.sciencebase.gov/catalog/item/5b4e1c3fe4b06a6dd17df2d3) folder's name.    
^**2**^ For a Product item, the **Fiscal Year** is derived from the associated Project item.  
:::

::: {.callout-note title="Note"} 
The SA Science Catalog entries are displayed in descending order of **Last Update Date**.
:::

## Architecture

At present, SA creates and edits metadata in mdEditor and then publish the
metadata to ScienceBase, where it can be channeled to the SA Science Catalog and
Data.gov. The mdTranslator tool is integrated with mdEditor so you can create
metadata once, and then convert and publish the metadata in your desired format,
such as mdJSON for the SA Science Catalog, sbJSON for ScienceBase, XML for
data.gov, and FGDC for geospatial data.

![A basic diagram detailing the Science Applications metadata system
architecture](/assets/metadata_system_architecture.png){width="800"}

1.  Items are imported from a database (like ScienceBase), or created directly
    in mdEditor.
2.  mdJSON files can also be stored in a local repository and then transmitted
    via a web service to ScienceBase. Alternately, the local files can be
    exported to a web accessible folder and then harvested by ScienceBase.
3.  The mdTranslator converts the mdJSON files into sbJSON (the ScienceBase JSON
    format) and XML.
4.  Items are exported from ScienceBase to: Data.gov as XML, the SA Science
    Catalog website as Projects and Products, or into mdEditor as mdJSON.

```{=html}
<!---
![A diagram of the Science Applications metadata system architecture that focuces on the relationship between MdEditor, ScienceBase, Data.gov, and the Science Applications Science Catalog. Blue arrow action are performed by the user. After a user publishes to ScienceBase from mdEditor, the dark brown arrow actions are triggered automatically by mdEditor and ScienceBase webservices. Green arrow actions are performed automatically by the external catalogs.](/assets/metadata_system_architecture2.png){width="800"}
--->
```
