---
title: "CASC Responsibilities"
editor: 
  markdown: 
    wrap: 80
---

The CASCs will complete the following metadata responsibilities for the CASC
records for co-funded projects and products, after being notified that a Service
metadata record has been created with associations to the CASC ScienceBase
records.

## Co-funded Protocol

### When a CASC project is co-funded with the Service:

CASC will add the following statement to the Summary in the CASC ScienceBase
record:

-   “This project was co-funded by the \[X, Y, Z\] Climate Adaptation Science
    Centers and the USFWS \[A, B, C\] region program. An alternate reference to
    this project can be found here\[insert SA ScienceBase URL\].”

Example: “This project was co-funded by the South Central Climate Adaptation
Science Center and the USFWS Gulf Coast Region. An alternate reference to this
project can be found
[here](https://www.sciencebase.gov/catalog/item/5a78be62e4b00f54eb1e849c).”

The Service will include a parallel statement in the Summary field for their
ScienceBase record, link back to the CASC record, and create the association in
ScienceBase.

### When a CASC product is co-funded with the Service:

CASC will add the following text to the Summary in the CASC ScienceBase record:

“This product was co-funded by USFWS \[A, B, C\] region and the \[X, Y, Z\]
Climate Adaptation Science Centers. An alternate reference to this product can
be found here\[insert SA ScienceBase URL\].”

Example: “This project was co-funded by USFWS Gulf Coast Region and the South
Central Climate Adaptation Science Center. An alternate reference to this
product can be found
[here](https://www.sciencebase.gov/catalog/item/5a78be62e4b00f54eb1e849c).”

The Service will include a parallel statement in the Summary field for their
ScienceBase record, link back to the CASC record, and create the association in
ScienceBase.

## Sub-Project Protocol

### If a CASC project is a sub-project of a Service project:

1.  Add the following text to the Summary in the CASC ScienceBase record: “This
    project is a sub-project of USFWS \[X\] region project described
    here\[insert LCC ScienceBase URL\].”
2.  Add the association in ScienceBase as a “subprojectOf” the SA metadata
    record.
