---
title: "Sub-Project Protocol"
editor: 
  markdown: 
    wrap: 80
---

## Applicability

Refer to this protocol if:

1.  A region or program funds a distinct portion or sub-project of a larger
    project (aka parent project) or a distinct product of project supported by
    another region or program, see 
    [Sub-project of FWS Region or Program Project](of-lcc-project.md).
2.  A FWS region or program funds a distinct portion of a CASC project or
    vice-versa, see [Sub-project of CASC Project](of-casc-project.md).

In this case, the funding information should only be entered in a project
metadata record once. If the funding for a sub-project is distributed
separately, then it can be included in the sub-project metadata. Otherwise, if
the sub-project was funded from a parent project and the funding allocation is
not distinctly identified, then all the funding information should be included
in the parent project metadata. Funding allocations should NOT be duplicated in
multiple metadata records.
