---
title: "Project Entry Overview"
editor: 
  markdown: 
    wrap: 80
---

The Project Entry Guidance section will cover how to create a metadata record
for an SA project.

## Before You Begin

### **Adjust your mdEditor** [**Settings**](../settings.md)**:**

**Metadata Repositories**: Make sure your default settings are correct for the
SA Science Catalog and data.gov. See [Settings](../settings.md).

**Parent Identifier:** In the publishing settings, enter your regional's SA
ScienceBase project folder's identifier in the "Default Parent Identifier"
field.

### **Select the Project Profile**:

After creating your project record initially and before you begin adding
metadata, select **Project** from the **Profile** drop-down in the main menu.
This will limit the number of available tabs and only show tabs that contain
fields that are applicable to project metadata.

![After selecting the Project profile, only the relevant tabs will be
displayed.](../.gitbook/assets/image%20%282%29.png)

### **Make sure your contacts are loaded into mdEditor:**

In mdEditor, contacts are created separately from individual records and then
stored within a library in mdEditor. Once contacts have been entered or imported
into mdEditor, they can be used in any metadata records.

To reduce unnecessary duplication of contacts, SA has a "seed list" of contacts
that include government agencies and partners that are often affiliated with
USFWS projects and products.

Insert LINK HERE TO SEED LIST.

{% hint style="danger" %} You should maintain a single list of your contacts.
Having duplicate copies of the same contact is not desirable. It can create
confusion as you edit and manage your metadata records and introduce unnecessary
errors. {% endhint %}

## Edit a Project

1.  Import or create your project record (see [workflow](../getting-started/)).
2.  Pick "project" as the **Resource Type**
3.  Select the Project Profile: from the Main Menu (Top Navigation Bar) select
    "**Project"** from the profile drop-down menu.
4.  Fill out metadata information for the following tabs:
    -   [Main Tab](record-main-copy.md)
    -   [Metadata Tab](metadata-tab.md)
    -   [Keywords Tab](keywords-tab.md)
    -   [Taxonomy Tab](taxonomy-tab-projects.md)
    -   [Extent Tab](extent-tab.md)
    -   [Documents Tab](documents-tab-projects.md)
    -   [Funding Tab](funding-tab.md)
5.  If applicable, [associate](associating-records.md) your project with other
    metadata records.

## Required Fields for Projects

### **Main Tab**

-   Title
-   Status
-   Language
-   Resource Type
-   Point of Contact
-   Main Citation
    -   Title
    -   Identifier
    -   Responsible Parties
    -   Date
    -   Online Resource URI
-   Description
    -   Abstract
-   Time Period
    -   Start Date
    -   End Date

### **Metadata Tab**

-   Metadata Status
-   Last Update Date
-   Metadata Contacts
-   Metadata Identifier
-   Parent Metadata
    -   Title
    -   Identifier
    -   Namespace
-   Metadata Repositories

### **Keywords Tab**

-   ISO Topic Category
-   SA Priority Area Category
-   SA Science Category
-   Conservation Action Open Standard
-   Anticipated Deliverables (Best Practice)
-   GCMD Keywords (Best Practice)

### Taxonomy Tab

-   Taxonomic classifications

### **Extent Tab**

-   Geographic Extent

### **Funding Tab**

-   Allocation
    -   AwardID
    -   Amount
    -   Currency
    -   Source
    -   Recipient
    -   Other Contacts\Administrator
    -   Matching Funds
-   Time Period
    -   Fiscal Year
