---
title: "Project Records: Overview"
editor: 
  markdown: 
    wrap: 80
---

This section will cover how to create a metadata record for an SA project.

## Before You Begin

### 1. Check mdEditor Settings

In the [Default](../settings.qmd#defaults) settings make sure 
**Metadata Repositories** includes "SA Science Catalog" and "data.gov".

In the [Publishing](../settings.qmd#publishing-settings) settings, under the 
**Default Parent Identifier:** ensure you entered your Region's Parent 
Identifier from the table below.

| USFWS Region     | Parent Identifier        |
|------------------|--------------------------|
| **Headquarters** | 645bfe94d34ec179a83822dc |
| **Region 1**     | 664f786bd34e702fe8747f80 |
| **Region 2**     | 645bfe4bd34ec179a83822ce |
| **Region 3**     | 645bfe56d34ec179a83822d0 |
| **Region 4**     | 645bfe5fd34ec179a83822d2 |
| **Region 5**     | 645bfe6ad34ec179a83822d4 |
| **Region 6**     | 645bfe76d34ec179a83822d6 |
| **Region 7**     | 645bfe80d34ec179a83822d8 |
| **Region 8**     | 645bfe8ad34ec179a83822da |
: {.striped .hover .bordered .md .allborder} 

<br/>

### 2. Select the "Project" profile

After initially creating your project record, but before you begin adding
metadata, select the metadata record's profile type. 
In the main menu's **Profile** drop-down options, select "**Project**".
This will limit the number of available tabs and only show tabs that contain
fields that are applicable to project metadata.

![After selecting the Project profile, only the relevant tabs will be
displayed.](../../assets/project_profile.png)

<br/>

### 3. Ensure your Contacts are loaded into mdEditor

In mdEditor, contacts are created separately from individual records and then
stored within a library in mdEditor. Once contacts have been entered or imported
into mdEditor, they can be used in any metadata records.

To reduce unnecessary duplication of contacts, SA has a "seed list" of contacts
that include government agencies and partners that are often affiliated with
USFWS projects and products 
[SA ScienceBase Community](https://www.sciencebase.gov/catalog/item/5b4e1c3fe4b06a6dd17df2d3).
item page

:::{.callout-warning icon=false} 
You should maintain a single list of your contacts.
Having duplicate copies of the same contact is not desirable. It can create
confusion as you edit and manage your metadata records and introduce unnecessary
errors. 
:::

## Edit a Project

1.  Import or create your Project record (see [workflow](../workflow/workflow_overview.qmd)).
2.  Pick **"project"** as the **Resource Type**
3.  Select the Project Profile: from the Main Menu (Top Navigation Bar) select
    "**Project"** from the profile drop-down menu.
4.  Fill out metadata information for the following tabs:   
          [Main Tab](main_tab_project.qmd)    
          [Metadata Tab](metadata_tab_project.qmd)    
          [Keywords Tab](keywords_tab_project.qmd)    
          [Taxonomy Tab](taxonomy_tab_project.qmd)    
          [Extent Tab](extent_tab_project.qmd)    
          [Documents Tab](documents_tab_project.qmd)    
          [Funding Tab](funding_tab_project.qmd)    
5.  If applicable, the [Associated Tab](associated_tab_project.qmd) allow your 
    project to be associated with other metadata records.

<!-- 
################### START OF COMMENTED OUT CODE ################################ 

### Required Fields for Projects

#### **Main Tab**

-   Title
-   Status
-   Language
-   Resource Type
-   Point of Contact
-   Main Citation
    -   Title
    -   Identifier
    -   Responsible Parties
    -   Date
    -   Online Resource URI
-   Description
    -   Abstract
-   Time Period
    -   Start Date
    -   End Date

#### **Metadata Tab**

-   Metadata Status
-   Last Update Date
-   Metadata Contacts
-   Metadata Identifier
-   Parent Metadata
    -   Title
    -   Identifier
    -   Namespace
-   Metadata Repositories

#### **Keywords Tab**

-   ISO Topic Category
-   SA Priority Area Category
-   SA Science Category
-   Conservation Action Open Standard
-   Anticipated Deliverables (Best Practice)
-   GCMD Keywords (Best Practice)

#### Taxonomy Tab

-   Taxonomic classifications

#### **Extent Tab**

-   Geographic Extent

#### **Funding Tab**

-   Allocation
    -   AwardID
    -   Amount
    -   Currency
    -   Source
    -   Recipient
    -   Other Contacts\Administrator
    -   Matching Funds
-   Time Period
    -   Fiscal Year

################### END OF COMMENTED OUT CODE ################################ 
-->
