---
title: "Contact Requirements Summary"
editor: 
  markdown: 
    wrap: 80
---

```{r, echo=FALSE}
setwd("../..")
source(file.path(getwd(), "config.R"))
```

The following compiles all of the required and recommended contact information
for project and product metadata. This information is also listed in the
specific metadata sections in the manual.

## Locations for Contact Information

Once your contacts have been created in mdEditor, there are five places in a
metadata record where you should add contacts.

*Please see the corresponding sections for which contacts should be added
where.*

1.  [Main Tab / Point of Contact](../project_records/main_tab_project.qmd#points-of-contact-required)
2.  [Main Tab / Citation / Responsible Parties](../project_records/main_tab_project.qmd#responsible-parties-required)
3.  [Metadata Tab / Contacts](../project_records/metadata_tab_project.qmd#metadata-contacts)
4.  [Funding Tab / Allocation](../project_records/funding_tab_project.qmd) (for Projects only)
5.  [Distribution Tab / Contacts](../product_records/distribution_tab_product.qmd) (for Products only)

### Main / Point of Contact

| Role                  | Contact                  | Requirements     |
|:----------------------|:-------------------------|:--------------|
| pointOfContact        | SA National Data Steward | [Required]`r req_style`      |
| pointOfContact        | Your Region Data Steward | [Best Practice]`r best_style` |
| pointOfContact        | Data Steward             | [Required]`r req_style`      |
| custodian             | Data Custodian           | [Best Practice]`r best_style` |
| principalInvestigator | Project PI               | [Best Practice]`r best_style` |
| administrator         | FWS Project Officer      | [Required]`r req_style` |
| administrator         | FWS Region               | [Required]`r req_style` |
| administrator         | FWS Program              | [Best Practice]`r best_style` |
: {.striped .hover .bordered .md .allborder} 

### Main / Citation / Responsible Parties

This must include a point of contact, but may also include other responsible
parties such as funders, partners, collaborators, and
contributors. Collaborators could be intellectual participants while
contributors could be intellectual and financial participants.

| Role                  | Contact        | Requirements |
|:----------------------|:---------------|:----------|
| principalInvestigator | Project PI     | [Required]`r req_style`  |
: {.striped .hover .bordered .md .allborder} 

### Metadata / Contacts

| Role           | Contact          | Requirements                |
|:---------------|:-----------------|:-------------------------|
| author         | See notes below  | [Required]`r req_style` (at least one) |
| publisher      | Default is FWS   | [Required]`r req_style` |
| pointOfContact | FWS Data Steward | [Required]`r req_style` |
: {.striped .hover .bordered .md .allborder}   

#### Role of **author**

-   At least one contact with the role of **author** is required.
-   The **author** does not necessarily have to be the data steward (e.g., 
    imported FGDC metadata can list the original author).
-   The **author** can be an individual or an organization.
-   You can enter your regional or program data manager as the **author**. If you
    prefer, you can use a generic data manager contact rather than an individual
    name.


### Funding / Allocation (for Projects only)

#### Source ([Required]`r req_style`)

Add the relevant contact for the **source** of the project funding. Source 
should be an organization, not an individual. For FWS projects, the default 
source is U.S. Fish and Wildlife Service. Regions or programs should be added 
as the funding **administrator** in the Other Contacts field.

::: {.callout-note icon=false}
Funding **source** should always identify the agency or
organization, rather than a sub-program or office. For example, all funding from
other FWS programs need to list U.S. Fish and Wildlife Service as the source
(and not list the source as Fisheries, specific Refuges, ES, etc.).
Clarifications on the exact program or office where the funding came from can be
done through the Funding/Other Contacts field (and choose the role of
**administrator**). 
:::

#### Recipient ([Required]`r req_style`)

Add the relevant contact for the **recipient** of the project funding. Recipient
should always be an organization, not an individual. For example, the Principal
Investigator would not be listed as the recipient, but their organization would
be listed. If there are multiple recipients for a project, they should be added 
as separate allocations.

The Principal Investigator may be added in the Other Contacts field as
**principalInvestigator**.

::: {.callout-note icon=false}
Funding administrator can also be used to differentiate
funding from different programs/offices within the same agency. For example, the
U.S. Fish and Wildlife Service can be identified as the funding source and the
funding administrator could include "Ecological Services" or a specific field
office. 
:::

### Distribution (for Products only)

Add the relevant contact for **distributor** of the product.
