---
title: "Requirements for Publishing"
editor: 
  markdown: 
    wrap: 80
---

Publishing requires the record to be a **valid record**, meaning that mdEditor
checks that all required fields for a mdJSON file are present before allowing a
record to be published.

::: {.callout-note}
Note: mdEditor does not check for SA specific
requirements as documented here. It only checks that the metadata meets ISO
requirements. Fulfilling SA requirements falls on the creator of the records.
Consult the [**Project Entry Guidance**](../project-entry-guidance/) and
[**Product Entry Guidance**](../product-entry-guidance/) sections for SA
requirements. 
:::

Publishing requires every record to have a parent Identifier that identifies the
ScienceBase folder where your record will be sent upon publishing. If you set up
your Default Parent Identifier in [Settings](../settings.md), then you do not
need to add a parent ID to your individual record. However, if you need to
publish your record to a location different than your default folder, then you
need to edit the Parent ID in your metadata record to the different location
(see [Metadata/Parent
Metadata](https://cookmt.gitbooks.io/mdeditor-for-lccs/content/record/main/metadata-tab.html#parent-metadata)).

::: {.callout-note} 
Note: Please use a testing folder before you update your
real records. (Consult the [**Instructions for Testing
Publishing**](https://github.com/tpatterson1996/lcc-metadata-manual/tree/287090b07635d0e76a714278ce1f6c4aac3594cc/publish/instructions-for-testing-publishing.md)
section of this manual for more information).
:::
