---
title: "Workflow: Overview"
editor: 
  markdown: 
    wrap: 80
---

## Suggested Workflow for SA Metadata and mdEditor

The following is a suggested workflow for using mdEditor to create, publish, and
save metadata records for SA projects and products.

### 1. Gather information 

Have information about your contacts, projects, and products on hand before you
begin creating metadata records. Key information to gather includes project
proposals, funding agreements and amounts, project reports, product information,
and contact information for individuals and organizations involved in the
projects.

### 2. Open mdEditor

The direct link to mdEditor is <https://go.mdeditor.org>. Choose the browser you
plan to use for mdEditor and bookmark this link.

mdEditor can also be accessed from its homepage at <https://www.mdeditor.org/>.
This site provides some background information and Frequently Asked Questions
about mdEditor.

Always hit ***Refresh*** in your browser before each work session (and
periodically throughout the session) to ensure that you are using the most
updated version of mdEditor.

### 3. Adjust settings

In mdEditor settings, set the SA-specific settings for importing from
ScienceBase, Metadata Repositories, and Publishing (See
[Settings](../settings.qmd)).

### 4. Create or import contacts

Contacts must be created or uploaded before they can be added to project and
product metadata records using the
[Contacts](../contact_records/contact_records_overview.qmd) entry form in
mdEditor.

Use the "contacts seed file" that contains pre-filled information and standard
naming conventions for all SA regions, common federal agencies, and the SA
Network Data Steward. (link to contact seed file here)

### 5. Create or import projects

For creating or importing metadata for a
[project](../project_records/project_records_overview.qmd) use one of the
following options based on whether or not you have already created a mdEditor
project record.

a.  If you do not have existing ScienceBase project records, create an mdEditor
    project record from scratch using the [Metadata from
    Scratch](metadata_from_scratch.qmd) workflow.

b.  If you have an existing ScienceBase project record that has not been edited
    in mdEditor, import the ScienceBase record to create a new mdEditor record
    using the [Metadata from ScienceBase](metadata_sciencebase_first.qmd)
    workflow.

c.  If you have already created an mdEditor record for the project, import the
    mdEditor file to [Metadata Editing /
    Re-Publishing](metadata_editing_republishing.qmd) workflow to continue
    editing.

### 6. Create or import products

For creating or importing metadata for a
[product](../product_records/product_records_overview.qmd) use one of the
following options based on whether or not you have already created a mdEditor
project record.

a.  If you do not have existing ScienceBase product records, create an mdEditor
    project record from scratch using the [Metadata from
    Scratch](metadata_from_scratch.qmd) workflow.

b.  If you have an existing ScienceBase product record that has not been edited
    in mdEditor, import the ScienceBase record to create a new mdEditor record
    using the [Metadata from ScienceBase](metadata_sciencebase_first.qmd)
    workflow.

c.  If you have already created an mdEditor record for the product, import the
    mdEditor file to [Metadata Editing /
    Re-Publishing](metadata_editing_republishing.qmd) workflow to continue
    editing.

### 7. Create or import data dictionaries

If a product record has a need for data
[dictionaries](../product_records/dictionaries_tab_product.qmd), create or
import one.

### 8. Complete metadata

Decide on your desired file management approach and complete your metadata
accordingly. See the [File Management](../metadata_file_management/metadata_file_management_overview.qmd)
section for options and instructions.

### 9. Create associations

For projects and/or products, associations can be either [associated from a
project](../project_records/associated_tab_project.qmd) or [associated from
a product](../product_records/associated_tab_product.qmd).

### 10. Publish your records

From the mdEditor interface, [publish](../publishing/publishing_overview.qmd)
the records to ScienceBase.

### 11. Export your records

Use the [Export](../metadata_file_management/export.qmd) function to export
records of your products, projects, and contacts for backup, transfer, or
sharing. You may want to export working backups before publishing depending on
your situation, but archival exports should be done after publishing since
publishing can alter records, like adding or changing a ScienceBase ID.

### 12. Review Science Catalog

The [SA Science Catalog](https://www.fws.gov/science/catalog/) updates overnight
so you should review newly-published records the day after you publish to
ScienceBase. This will be one of your best quality control checks.

