---
title: "Metadata Requirements"
fig-cap-location: bottom
---

```{r, echo=FALSE}
setwd("..")
source(file.path(getwd(), "config.R"))
```

## Projects and Products
Metadata fields have different requirements for **Project** and **Product** records. 

       [Required]`r req_style`: required for all records of that type.   
       [If Applicable]`r if_style`: required if the information is applicable and available.    
       [Best Practice]`r best_style`: recommended, but not required. 


### Main Tab    

| Metadata Field                | Project Records   | Product Records   |
|:------------------------------|:-------------|:-------------|
| Basic Information     | | |
|        Title          | [Required](project_records/main_tab_project.qmd#title-required)`r req_style`  |                                                                                                                                                  [Required](product_records/main_tab_product.qmd#title-required)`r req_style`           |
|        Status         | [Required](project_records/main_tab_project.qmd#status-required)`r req_style` |                                                                                                                                                  [Required](product_records/main_tab_product.qmd#status-required)`r req_style`      |
| Default Locale        | [Required](project_records/main_tab_project.qmd#default-locale-required)`r req_style` |                                                                                                                                          [Required](product_records/main_tab_product.qmd#default-locale-required)`r req_style`  |
| Resource Type         | [Required](project_records/main_tab_project.qmd#resource-types-required)`r req_style` |                                                                                                                                          [Required](product_records/main_tab_product.qmd#resource-types-required)`r req_style`  |
| Points of Contact     | | |
|        pointOfContact | [Required](project_records/main_tab_project.qmd#points-of-contact-required)`r req_style` |                                                                                                                                       [Required](product_records/main_tab_product.qmd#points-of-contact-required)`r req_style` |
|        administrator  |  [Required](project_records/main_tab_project.qmd#points-of-contact-required)`r req_style` |                                                                                                                                       [Required](product_records/main_tab_product.qmd#points-of-contact-required)`r req_style` |
|        custodian      | [Required](project_records/main_tab_project.qmd#points-of-contact-required)`r req_style` |                                                                                                                                       [Required](product_records/main_tab_product.qmd#points-of-contact-required)`r req_style` |
|        owner          |  [Required](project_records/main_tab_project.qmd#points-of-contact-required)`r req_style` |                                                                                                                                       [Required](product_records/main_tab_product.qmd#points-of-contact-required)`r req_style` |
|        Others (multiple)  | [If Applicable](project_records/main_tab_project.qmd#points-of-contact-required)`r if_style` |                                                                                                                                  [If Applicable](product_records/main_tab_product.qmd#points-of-contact-required)`r if_style` |
| Citation                      | | |
|        Title                  | [Required](project_records/main_tab_project.qmd#title-required-1)`r req_style` |                                                                                                                                                 [Required](product_records/main_tab_product.qmd#title)`r req_style`|
|        Dates                  |||
|               lastUpdate <a href="#footnote1" style="color:blue;font-weight:bold;vertical-align:super;font-size:smaller;text-decoration: none;">TEST</a> | [Required](project_records/main_tab_project.qmd#dates-required)`r req_style` |                                                                                                                                                   [Required](product_records/main_tab_product.qmd#dates-required)`r req_style`|
|               Others (multiple)  | [If Applicable](project_records/main_tab_project.qmd#dates-required)`r if_style` |                                                                                                                                               [If Applicable](product_records/main_tab_product.qmd#dates-required)`r if_style` |
|        Responsible Parties      | | |
|               pointOfContact    | [Required](project_records/main_tab_project.qmd#responsible-parties-required)`r req_style` |                                                                                                                                     [Required](product_records/main_tab_product.qmd#responsible-parties-required)`r req_style`|
|               principalInvestigator    | [Required](project_records/main_tab_project.qmd#responsible-parties-required)`r req_style` |                                                                                                                                     [Required](product_records/main_tab_product.qmd#responsible-parties-required)`r req_style`|
|               Others (multiple) | [If Applicable](project_records/main_tab_project.qmd#responsible-parties-required)`r if_style` |                                                                                                                                 [If Applicable](product_records/main_tab_product.qmd#responsible-parties-required)`r if_style`|
|        Online Resource        |  |  |
|               Name            | [If Applicable](project_records/main_tab_project.qmd#online-resource-if-applicable)`r if_style`|                                                                                                                                 [If Applicable](product_records/main_tab_product.qmd#online-resource-if-applicable)`r if_style`  |
|               URL             | [If Applicable](project_records/main_tab_project.qmd#online-resource-if-applicable)`r if_style`|                                                                                                                                 [If Applicable](product_records/main_tab_product.qmd#online-resource-if-applicable)`r if_style`  |
|               Function        | [If Applicable](project_records/main_tab_project.qmd#online-resource-if-applicable)`r if_style`|                                                                                                                                 [If Applicable](product_records/main_tab_product.qmd#online-resource-if-applicable)`r if_style`  |
|        Identifier             | | |
|               Identifier      | [Required](project_records/main_tab_project.qmd#identifier-required)`r req_style` |                                                                                                                                              [Required](product_records/main_tab_product.qmd#identifier-required)`r req_style`   |
|               Namespace       | [Required](project_records/main_tab_project.qmd#namespace-required)`r req_style` |                                                                                                                                               [Required](product_records/main_tab_product.qmd#namespace-required)`r req_style`   |
| Description                   | | |
|        Abstract               | [Required](project_records/main_tab_project.qmd#abstract-required)`r req_style`     |                                                                                                                                            [Required](product_records/main_tab_product.qmd#abstract-required)`r req_style`      |
| Time Period                   | | |
|        Start Date             | [Required](project_records/main_tab_project.qmd#time-period)`r req_style`  |                                                                                                                                                     [If Applicable](product_records/main_tab_product.qmd#time-period)`r if_style`  |
|        End Date               | [Required](project_records/main_tab_project.qmd#time-period)`r req_style`  |                                                                                                                                                     [Required](product_records/main_tab_product.qmd#time-period)`r req_style`   |
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"} 

<a id="footnote1" style="color:blue;font-weight:bold;vertical-align:super;font-size:smaller;">1</a>
<span style="font-size:90%;">The **lastUpdated** date is used in the Science Catalog to ensure that newer records appear at the top of the default list.</span>


### Metadata Tab    
| Metadata Field                | Project Records   | Product Records   |
|:------------------------------|:-------------|:-------------|
| Metadata Status   | [Required](project_records/metadata_tab_project.qmd#metadata-status-required)`r req_style` | [Required](product_records/metadata_tab_product.qmd#metadata-status-required)`r req_style` | 
| Dates             | [Required](project_records/metadata_tab_project.qmd#dates-required)`r req_style`  | |
| Metadata Contacts |        |                                                                      |
|        Author     | [Required](project_records/metadata_tab_project.qmd#metadata-contacts)`r req_style`   | [Required](product_records/metadata_tab_product.qmd#metadata-contacts)`r req_style`|
|        Publisher  | [Required](project_records/metadata_tab_project.qmd#metadata-contacts)`r req_style`   | [Required](product_records/metadata_tab_product.qmd#metadata-contacts)`r req_style`|
|        Point of Contact | [Required](project_records/metadata_tab_project.qmd#metadata-contacts)`r req_style`   | [Required](product_records/metadata_tab_product.qmd#metadata-contacts)`r req_style`|
| Metadata Identifier     | [Required](project_records/metadata_tab_project.qmd#metadata-identifier-required)`r req_style` | [Required](product_records/metadata_tab_product.qmd#metadata-identifier-required)`r req_style`|
| Parent Metadata         | [Required](project_records/metadata_tab_project.qmd#parent-metadata-required)`r req_style`     | [Required](product_records/metadata_tab_product.qmd#parent-metadata-required)`r req_style`|
| Metadata Repositories   | [Required](project_records/metadata_tab_project.qmd#metadata-repositories-required)`r req_style` | [Required](project_records/metadata_tab_project.qmd#metadata-repositories-required)`r req_style`|
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"}    

::: {style="font-size: 50%;"}
<br/>  
:::  

### Keywords Tab   
| Metadata Field                | Project Records   | Product Records   |
|:------------------------------|:-------------|:-------------|
| ISO Topic Category | [Required](project_records/keywords_tab_project.qmd#iso-topic-category-required)`r req_style` |                                                                                                                                  [Required](product_records/keywords_tab_product.qmd#iso-topic-category-required)`r req_style` |
| SA Priority Area | [Required](project_records/keywords_tab_project.qmd#sa-priority-area-required)`r req_style` |                                                                                                                                    [Required](product_records/keywords_tab_product.qmd#sa-priority-area-required)`r req_style` |
| SA Science Topic  | [Required](project_records/keywords_tab_project.qmd#science-topic-required)`r req_style` |                                                                                                                                       [Required](product_records/keywords_tab_product.qmd#science-topic-required)`r req_style` |
| Conservation Action Open Standard | [If Applicable](project_records/keywords_tab_project.qmd#conservation-action-open-standard-required-if-applicable)`r if_style` |                                                                                                 [If Applicable](product_records/keywords_tab_product.qmd#conservation-action-open-standard-required-if-applicable)`r if_style` |
| Global Change Master Directory (GCMD)  | [Best Practice](project_records/keywords_tab_project.qmd#global-change-master-directory-gcmd-best-practice)`r best_style` |                                                                                                      [Best Practice](product_records/keywords_tab_product.qmd#global-change-master-directory-gcmd-best-practice)`r best_style` |
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"}   

::: {style="font-size: 50%;"}
<br/>  
::: 

### Extent Tab 
| Metadata Field       | Project Records   | Product Records   |
|:------------------------------------|:----------|:----------|
| Extent|[Required](project_records/extent_tab_project.qmd#add-taxonomic-system#creating-extents)`r req_style` | [Required](product_records/extent_tab_product.qmd#creating-extents)`r req_style` |
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"}  
 
::: {style="font-size: 50%;"}
<br/>  
::: 

### Taxonomy Tab 
| Metadata Field       | Project Records   | Product Records   |
|:---------------------|:-------------------|:-------------------|
| Taxonomic System         |[If Applicable](project_records/taxonomy_tab_project.qmd#add-taxonomic-system)`r if_style` | [If Applicable](product_records/taxonomy_tab_product.qmd#add-taxonomic-system)`r if_style`|
| Taxonomic Classification |[If Applicable](project_records/taxonomy_tab_project.qmd#add-taxonomic-system)`r if_style` | [If Applicable](product_records/taxonomy_tab_product.qmd#add-taxonomic-system)`r if_style`|
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"} 

::: {style="font-size: 50%;"}
<br/>  
::: 

### Distribution Tab
| Metadata Field                | Project Records   | Product Records   |
|:------------------------------|:-------------|:-------------|
| Distributor                                      | | |
|        Contacts                                  | | [If Applicable](product_records/distribution_tab_product.qmd#contacts-and-role-if-applicable)`r if_style`    |
|        Role                                      | | [If Applicable](product_records/distribution_tab_product.qmd#contacts-and-role-if-applicable)`r if_style`    |
| Transfer Options                                 | | |
|        Online Options                     | | |
|               Name                        |   | [If Applicable](product_records/distribution_tab_product.qmd#tname-if-applicable)`r if_style`    |
|               URI                              |   | [If Applicable](product_records/distribution_tab_product.qmd#uri-if-applicable)`r if_style`    |
|               Function                         |   | [If Applicable](product_records/distribution_tab_product.qmd#function-if-applicable)`r if_style`    |
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"}   

::: {style="font-size: 50%;"}
<br/>  
::: 

### Constraints Tab   
| Metadata Field                | Project Records   | Product Records   |
|:------------------------------|:-------------|:-------------|
| Constraint Type             |                  | [Required](product_records/constraints_tab_product.qmd#constraint-type-required)`r req_style`     |
| Legal                       |                  |                                                                                         |
|        Access Constraints   |                  | [Required](product_records/constraints_tab_product.qmd#legal)`r req_style`     |
|        Use Constraints      |                  | [If Applicable](product_records/constraints_tab_product.qmd#legal)`r if_style`    |
| Security                    |                  |                                    |
|        Classification       |                  | [If Applicable](product_records/constraints_tab_product.qmd#security)`r if_style`    |
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"}   

::: {style="font-size: 50%;"}
<br/>  
::: 

### Funding Tab
| Metadata Field                | Project Records   | Product Records   |
|:------------------------------|:-------------|:-------------|
| Allocation                    | | | 
|        Amount                 | [Required](project_records/funding_tab_project.qmd#amount-required)`r req_style`   |            | 
|        Currency               | [Required](project_records/funding_tab_project.qmd#currency-required)`r req_style`   |            | 
|        Award ID               | [Required](project_records/funding_tab_project.qmd#award-id-required)`r req_style` |            | 
|        Source                 | [Required](project_records/funding_tab_project.qmd#source-required)`r req_style`   |            | 
|        Recipient              | [Required](project_records/funding_tab_project.qmd#recipient-required)`r req_style`    |            | 
|        Other Contacts (multiple)  | [Required](project_records/funding_tab_project.qmd#other-contacts-required)`r req_style`|            | 
|        Marked Funds | [If Applicable](project_records/funding_tab_project.qmd#marked-funds-if-applicable)`r if_style` |            | 
| Time Period         | | | 
|        Dates        | [Required](project_records/funding_tab_project.qmd#dates-required)`r req_style` |  | 
| Description (multiple) | [Best Practice](project_records/funding_tab_project.qmd#description-best-practice)`r best_style` |  | 
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"}   

::: {style="font-size: 50%;"}
<br/>  
::: 

## Contacts
Certain metadata fields are required for Individual or Organization contacts.  

### Contacts Information
| Metadata Field                | Individual    | Organization    |
|:------------------------------|:-------------|:-------------|
| Type                | [Required](contact_records/individual_contacts.qmd#create-a-new-contact)`r req_style`   | [Required](contact_records/organization_contacts.qmd#create-a-new-contact)`r req_style`   |
| Individual Name     | [Required](contact_records/individual_contacts.qmd#create-a-new-contact)`r req_style`   |                                                                                               |
| Organizational Name |                                                                                             | [Required](contact_records/organization_contacts.qmd#create-a-new-contact)`r req_style`   |
| Position Name       | [If Applicable](contact_records/organization_contacts.qmd#create-a-new-contact)`r if_style` |                                                                                               |
| Contact Type        | [Required](contact_records/individual_contacts.qmd#create-a-new-contact)`r req_style`   | [Required](contact_records/organization_contacts.qmd#create-a-new-contact)`r req_style`   |
| Member Organization | [Required](contact_records/individual_contacts.qmd#create-a-new-contact)`r req_style`   |                                                                                               |
| Email Address       | [Required](contact_records/individual_contacts.qmd#create-a-new-contact)`r req_style`   | [Required](contact_records/organization_contacts.qmd#create-a-new-contact)`r req_style`   |
| Online Resource     |                                                                                             | [Required](contact_records/organization_contacts.qmd#create-a-new-contact)`r req_style`   |
| Physical Address    | [Best Practice](contact_records/individual_contacts.qmd#create-a-new-contact)`r best_style` | [Best Practice](contact_records/organization_contacts.qmd#create-a-new-contact)`r best_style` |
| Logo                |                                                                                             | [Best Practice](contact_records/organization_contacts.qmd#create-a-new-contact)`r best_style` |
: {.striped .hover .bordered .sm .allborder tbl-colwidths="[50, 25, 25]"}   

<br/>
