---
title: "Copy Records"
editor: 
  markdown: 
    wrap: 80
---

The **Copy** button is located in the mdEditor action menu on the right-hand
side of the screen. The Copy Button allows you to make a duplicate of an
existing metadata record.

## Copying Records

**Making a copy of a record can be used to**:

-   Start a new product, project, or contact record.
-   Populate multiple products faster (e.g., multiple workshop reports, a poster
    based on a publication).
-   Create a "template record" for a project that can be used as a starting
    place for each full metadata record. A template record can contain
    information commonly used across your projects or products (such as SA
    contacts).

**Use the Copy button carefully**:

::: {.callout-note appearance="minimal"}
Making a copy will generate a new Record ID for the copied record and be named
“Copy of …”. All the other info will remain the same including associations. The
“Metadata Identifier” is NOT copied but any identifiers in the Main Citation
WILL be copied.
:::

::: {.callout-warning appearance="minimal"}}
**Warning**: It is extremely important to review all copied identifiers and 
delete any that do not apply to the new record. Leaving in identifiers that do 
not belong could result in your new item being published to the wrong location
:::

Before saving, carefully review all information in copied record to ensure all
copied info is still relevant to the copied record, particularly any
identifiers.
